/* ============================================================
   SIGNAL DICTIONARY — part H: terms introduced by Zone 6.
   ============================================================ */

DICT.push(
  {
    id: 'ring-buffer', t: 'ring buffer (FIFO)', c: 'ARCHITECTURE',
    plain: 'A buffer of a fixed size, set aside once up front and treated as a circle: one thread writes at the head, another reads at the tail, and two atomic positions keep them coordinated. First-In-First-Out (FIFO) — a stream crosses the thread boundary and nobody ever waits.',
    why: 'It\'s THE lock-free vehicle for streams: meter data, visualizer samples, MIDI events to the UI. The audio thread pushes without blocking; the reader drains at its leisure; a full ring triggers a chosen policy (drop, overwrite) — never a stall.',
    studio: 'The kitchen pass in a restaurant: cooks put plates up, servers take them away, and neither ever stops the other. If the pass fills, the policy decides — but nobody stands still holding a plate.',
    uses: ['Meter/visualizer data audio→UI', 'MIDI event streams', 'Any producer/consumer pair'],
    viz: { t: 'fifo' },
    mistake: 'Growing the ring when it fills — growth is allocation, the forbidden verb on the audio thread. The ring\'s size is bought in prepareToPlay; fullness is handled by policy, chosen on purpose.',
    remember: 'One writes, one reads, atomic positions between them — streams cross, nobody waits.',
    related: ['lock-free', 'atomic', 'audio-thread', 'allocation'],
    appears: [{ z: 2, label: 'lock-free FIFOs' }, { z: 6, node: 'r4' }, { z: 6, node: 'p16' }],
    aka: ['fifo', 'circular buffer', 'AbstractFifo'],
    search: ['queue between threads', 'producer consumer', 'meter data', 'lock free queue'],
  },
  {
    id: 'double-buffering', t: 'double buffering', c: 'ARCHITECTURE',
    plain: 'Two copies of a data bundle plus one atomic pointer: the audio thread reads the live copy while the writer prepares the other completely, then flips the pointer. Readers see all-old or all-new — never a half-updated mix.',
    why: 'Atomics carry one value; bundles that must change TOGETHER (a wavetable, an EQ curve, a preset\'s settings) need this: the flip turns a slow multi-field update into a single safe atomic operation.',
    studio: 'Changing the menu board by printing a whole new board and swapping it in one motion — never by editing the hanging board while customers read it.',
    uses: ['Wavetable swaps', 'Curve/EQ updates', 'Preset data reaching the audio thread'],
    mistake: 'Editing the LIVE copy "just this once" — the reader sees a half-updated bundle mid-block, which is the exact tear the pattern exists to prevent. Always build the back copy, then flip.',
    remember: 'Build the hidden copy fully, flip one pointer — all-old or all-new, never between.',
    related: ['atomic', 'lock-free', 'ring-buffer', 'race-condition'],
    appears: [{ z: 6, node: 'r4' }, { z: 6, node: 'p16' }],
    aka: ['buffer flip', 'ping-pong buffers'],
    search: ['swap safely', 'update wavetable', 'atomic pointer flip'],
  },
  {
    id: 'assertion', t: 'assertion (jassert)', c: 'DEBUGGING',
    plain: 'A statement of something that must be true — jassert(note <= 127) — checked in Debug builds (halting in the debugger at that exact line when false) and compiled to NOTHING in Release. A tripwire for developers that costs users zero.',
    why: 'Assertions catch lies the moment they\'re told, at the line where the assumption lives — instead of three functions later as a mystery. Free in the shipped build, they\'re documentation with teeth: write hundreds.',
    studio: 'Gaffer tape marks on the stage: BAND STANDS HERE. Rehearsal (Debug) enforces them loudly; on show night (Release) the marks are gone and everyone already stands right.',
    uses: ['Contracts (note 0–127, vel 0–1)', 'Wiring checks (pointer set in prepare)', 'Invariants (phase in range)'],
    mistake: 'Putting side effects inside: jassert(loadFile(path)) — in Release the WHOLE line vanishes, call included, creating a bug that exists only where you can\'t debug it. Do the work, then assert the result.',
    remember: 'Assert facts, not weather — loud in Debug, gone in Release, side effects never.',
    related: ['debug-build', 'release-build', 'stack-trace'],
    appears: [{ z: 6, node: 'r10' }, { z: 6, node: 'rc4' }],
    aka: ['jassert', 'invariant check', 'assert'],
    search: ['check assumption', 'debug break', 'invariant', 'tripwire'],
  },
  {
    id: 'profiling', t: 'profiling', c: 'PERFORMANCE',
    plain: 'Measuring where a running program actually spends its time, using a profiler that samples execution and reports hotspots. The results are famously surprising — the "expensive-looking" code is rarely the real cost.',
    why: 'Intuition about performance is reliably wrong: the true hotspots are boring (a pow per sample, a string lookup in a loop, denormals). The professional loop — measure, fix ONE thing, measure again — spends effort only where numbers convict.',
    studio: 'The solo button. Everyone SWEARS they know which track is muddy; the solo button embarrasses everyone weekly. Profile before you touch a single fader.',
    uses: ['Finding real hotspots', 'Verifying a fix actually helped', 'CPU budgeting for worst cases'],
    viz: { t: 'cpumeter' },
    mistake: 'Optimizing what LOOKS expensive — rewriting DSP math while an atomic string-lookup sits in the sample loop. "Looks expensive" and "is expensive" barely correlate; that\'s why the tool exists.',
    remember: 'Measure, fix one convicted line, measure again. Unmeasured optimization is guessing.',
    related: ['cpu', 'simd', 'denormals'],
    appears: [{ z: 6, node: 'r11' }, { z: 6, node: 'p18' }],
    aka: ['profiler', 'hotspot analysis'],
    search: ['cpu usage', 'find slow code', 'hotspot', 'measure performance'],
  },
  {
    id: 'simd', t: 'SIMD', full: 'Single Instruction, Multiple Data', c: 'PERFORMANCE',
    plain: 'CPU instructions that apply one operation to 4, 8 or 16 floats at once. Audio — the same math over long runs of samples — is the natural customer: buffer-wide multiplies and adds go several times faster.',
    why: 'You mostly get it without writing it: compilers auto-vectorize simple contiguous loops, and juce::FloatVectorOperations is SIMD someone already wrote and tested. Hand-written intrinsics are the last resort, for profiler-convicted loops only.',
    studio: 'One fader move that adjusts eight channels of a VCA group at once — one gesture, many signals, exactly the same operation applied to each.',
    uses: ['Buffer-wide gain/mix (FloatVectorOperations)', 'Auto-vectorized sample loops', 'Hand-tuned hot paths (rare)'],
    mistake: 'Hand-writing intrinsics everywhere "because SIMD is faster." Unreadable, unportable, and usually beaten by hoisting a pow out of the loop — measure first, library second, intrinsics last.',
    remember: 'One instruction, many floats — reach it via simple loops and the library before intrinsics.',
    related: ['cpu', 'profiling', 'audio-buffer'],
    appears: [{ z: 6, node: 'r11' }, { z: 6, node: 'p18' }],
    aka: ['vectorization', 'FloatVectorOperations', 'sse', 'avx', 'neon'],
    search: ['faster loops', 'vector math', 'parallel floats'],
  },
  {
    id: 'unit-test', t: 'unit test', c: 'TOOLS',
    plain: 'A small automated check that runs one piece of code with known inputs and verifies the output — midiToHz(69) must equal 440, a full pool\'s findVictim must return the releasing voice. No host, no sound card, no ears required.',
    why: 'Each test freezes one claim forever: every build re-proves the pitch map, the wrap, the stealing ladder. When a refactor breaks an assumption, a test names the exact broken fact in seconds.',
    studio: 'Checking each cable with a tester before the show — one cable, one light, pass or fail. You don\'t debug the whole rig at soundcheck; you prove the pieces first.',
    uses: ['DSP math (pitch, ratios, wraps)', 'Voice logic (allocation, stealing)', 'State round-trips'],
    viz: { t: 'testpipe' },
    mistake: 'Writing tests only after bugs ship, as penance. The pro habit: every bug fixed gets a test that would have caught it — the suite becomes a museum of mistakes you\'ll never make twice.',
    remember: 'One piece, known input, verified output — a lesson\'s claim frozen into code.',
    related: ['regression-test', 'golden-render', 'assertion'],
    appears: [{ z: 6, node: 'r12' }],
    aka: ['unit testing', 'test suite'],
    search: ['test function', 'automated check', 'prove correct'],
  },
  {
    id: 'regression-test', t: 'regression test', c: 'TOOLS',
    plain: 'A test that proves something which USED to work still works — catching changes you didn\'t mean to make. In audio, the flagship is the golden render: fixed input through the plugin, output compared bit-for-bit against a blessed reference.',
    why: 'Refactors, optimizations and "harmless" fixes all carry the same risk: accidental change. Regression tests make the past enforceable — the build fails the moment today\'s output disagrees with the promise.',
    studio: 'The mastering engineer\'s null test: flip polarity, sum against the reference — silence means identical. A regression suite nulls your whole plugin against its own history, every build.',
    uses: ['Golden renders (sound identity)', 'Old-version preset files all loading', 'Bug-fix tests that pin each fix'],
    mistake: 'Loosening the tolerance until a failing test passes. The test was the messenger; the change was real. Investigate, then either fix the code or re-bless deliberately — never negotiate with the ruler.',
    remember: 'The past, enforceable: what worked keeps working, or the build says otherwise.',
    related: ['golden-render', 'unit-test', 'state-versioning'],
    appears: [{ z: 6, node: 'r12' }, { z: 6, node: 'rr3' }],
    aka: ['regression suite', 'regression testing'],
    search: ['still works', 'accidental change', 'old sessions test'],
  },
  {
    id: 'golden-render', t: 'golden render', c: 'TOOLS',
    plain: 'A stored reference rendering — fixed MIDI, fixed settings, fixed rate — that the plugin\'s current output is compared against on every build, within a tiny float tolerance. Any difference means the sound changed.',
    why: 'It answers the one question refactors can\'t answer themselves: "did the sound change?" Match the gold and you can rebuild the engine fearlessly; intentional changes re-bless a new gold in a commit that says so.',
    studio: 'The approved master: every test pressing is compared against it. A plant that ships pressings that "sound about the same" doesn\'t keep clients — identical is the standard, and identical is checkable.',
    uses: ['Refactor safety', 'Release gates', 'Cross-platform consistency checks'],
    viz: { t: 'testpipe' },
    mistake: 'Time-seeded randomness in the DSP (noise oscillators!) — every render becomes unique and no gold can ever pass. Testable synths seed deterministically; determinism is what makes proof possible.',
    remember: 'The sound, frozen: same input must yield the same output, or the build fails.',
    related: ['regression-test', 'unit-test', 'white-noise'],
    appears: [{ z: 6, node: 'r12' }, { z: 6, node: 'ro1' }, { z: 6, node: 'p19' }],
    aka: ['golden master', 'reference render', 'null test'],
    search: ['compare output', 'reference audio', 'did the sound change'],
  },
  {
    id: 'plugin-validation', t: 'plugin validation', c: 'PLUGIN DEV',
    plain: 'Automated entrance exams that torture a plugin with host behavior that\'s extreme but perfectly legal: pluginval (open source — VST3 and AU) and auval (Apple\'s, run by Logic before trusting any AU). Odd lifecycle orders, 0-sample blocks, rapid rate changes, state chaos.',
    why: 'Everything a validator does, some real host somewhere does eventually — validation concentrates a year of edge cases into a minute you can debug locally. Crash Monday in the validator, not Friday on a customer\'s stage.',
    studio: 'Venue security testing your rig harder than any audience will: cables yanked, power cycled, inputs slammed — because "it worked at rehearsal" is not a plan for 50,000 people.',
    uses: ['Pre-release gates (strictness 10)', 'auval for Logic/GarageBand', 'CI runs on every build'],
    mistake: 'Running validation once at the end, as a formality. Run it from week one — contract bugs found early are architecture decisions you can still change cheaply.',
    remember: 'Concentrated reality: pass the exam before your users administer it for you.',
    related: ['vst3', 'au', 'aax', 'preparetoplay'],
    appears: [{ z: 6, node: 'r13' }, { z: 6, node: 'p19' }, { z: 6, node: 'boss6' }],
    aka: ['pluginval', 'auval', 'host compatibility'],
    search: ['daw rejects plugin', 'logic validation', 'test in hosts'],
  },
  {
    id: 'stack-trace', t: 'stack trace', c: 'DEBUGGING',
    plain: 'The chain of function calls in flight when a program crashed, newest first: frame 0 is where it died; each frame below is the caller. Crash logs are stack traces plus the faulting address — a map with an X on it.',
    why: 'Customer crashes arrive without repro steps — the trace IS the repro: read top-down to your first frame, decode the address (0x0/near-zero = null(+offset); garbage = use-after-free; inside the allocator = earlier heap damage), and you have a suspect list.',
    studio: 'A flight recorder: it doesn\'t stop the incident, but it turns "it went down somewhere" into a timeline ending at an exact point — and recorder-readers prevent the NEXT one.',
    uses: ['Decoding customer crash logs', 'Debugger stops', 'Crash-reporting dashboards'],
    viz: { t: 'stackviz' },
    mistake: 'Assuming the crash site is the bug site. Heap corruption divorces them: the scribble happened earlier, elsewhere — the allocator merely tripped over the damage. The trace says WHERE it died, not always where it was wounded.',
    remember: 'Frame 0 is where, the address is what kind, the walk down is how it got there.',
    related: ['debugger', 'undefined-behavior', 'assertion', 'dangling-pointer'],
    appears: [{ z: 6, node: 'r14' }],
    aka: ['backtrace', 'crash log', 'call stack'],
    search: ['crash report', 'read crash', 'null pointer', 'debugging crash'],
  },
  {
    id: 'versioning', t: 'versioning (semver)', c: 'PLUGIN DEV',
    plain: 'Semantic versioning gives MAJOR.MINOR.PATCH numbers meaning: PATCH fixes bugs (nothing else changes), MINOR adds features compatibly (old sessions untouched), MAJOR may break things — loudly announced.',
    why: 'For plugins, the version number is a promise producers rely on mid-project: "is this update safe for my album?" 1.0.1 must mean yes. Truthful bumping is a trust system, and trust is the actual product.',
    studio: 'Catalog numbers on releases: the remaster (patch) plays in the same set, the deluxe edition (minor) adds tracks without changing the album, and the re-recording (major) says so on the cover.',
    uses: ['Release numbering', 'Update-safety signals to users', 'Changelog structure'],
    viz: { t: 'shipcheck' },
    mistake: 'Treating the numbers as marketing ("2.0 sounds better than 1.6"). Producers read them as compatibility contracts — inflating them teaches your users to fear your updates.',
    remember: 'PATCH fixes, MINOR adds compatibly, MAJOR breaks loudly — the number is a promise.',
    related: ['state-versioning', 'plugin-validation', 'preset'],
    appears: [{ z: 6, node: 'r15' }],
    aka: ['semantic versioning', 'semver', 'release numbering'],
    search: ['version number', 'update safe', 'changelog'],
  },
  {
    id: 'state-versioning', t: 'version-safe state', c: 'PLUGIN DEV',
    plain: 'State designed to survive time: a version stamp written into every save, defaults named on every read (missing properties resolve harmlessly), explicit migration when meanings change — and parameter IDs that never, ever change.',
    why: 'State written by v1.0 will be loaded by v1.4 for years. The golden rule: old sessions must sound IDENTICAL — new parameters default to neutral, and renamed IDs silently orphan every saved value and automation lane, which is why renaming is forbidden.',
    studio: 'A tape archive where every reel is labeled with the machine that made it, the playback deck aligns to the REEL\'s era, and nobody relabels old reels to match this year\'s naming scheme.',
    uses: ['getProperty with defaults', 'stateVersion stamps', 'Migration on load', 'ID discipline'],
    viz: { t: 'presetlife' },
    mistake: 'Testing state by saving and loading in the SAME build. The bugs live across versions — keep a state file from every release and load them ALL with every new build.',
    remember: 'Old sessions are sacred: stamp the version, default the missing, never touch an ID.',
    related: ['preset', 'valuetree', 'versioning', 'regression-test'],
    appears: [{ z: 6, node: 'r9' }, { z: 6, node: 'p17' }],
    aka: ['preset compatibility', 'backwards compatibility', 'migration'],
    search: ['old sessions', 'preset broke', 'update changed sound', 'compatibility'],
  }
);
