/* ============================================================
   SIGNAL DICTIONARY — part A: Basics, C++, Memory.
   Parts B (audio/DSP/synth) and C (JUCE/plugin-dev/MIDI/tools)
   push onto DICT in data_glossary_b.js / data_glossary_c.js.

   Entry shape:
   { id, t: term, full?: spelled-out name, c: category,
     plain:   plain English, no jargon
     why:     why it matters for building a VST
     studio:  music-production analogy
     uses:    where it shows up in real plugins (chips)
     viz?:    diagram spec (Viz)
     mistake: common beginner mistake
     remember: one sentence to keep forever
     related: [ids] — clickable
     appears: [{z, node?, label?}] — curriculum appearances
     aka?:    alternative names/abbreviations for search
     search?: beginner-wording search keywords }
   ============================================================ */

const DICT_CATS = ['ALL', 'BASICS', 'C++', 'MEMORY', 'AUDIO CODE', 'DSP', 'SYNTHS', 'EFFECTS', 'MIDI', 'JUCE', 'PLUGIN DEV', 'AUDIO ENG', 'MATH', 'TOOLS', 'DEBUGGING', 'PERFORMANCE', 'ARCHITECTURE', 'DAWS'];

const DICT = [

  /* ================= BASICS ================= */
  {
    id: 'variable', t: 'variable', c: 'BASICS',
    plain: 'A named slot that remembers one value. You give it a name, put a value in, and read or change it later. That\'s it — a labeled box that holds a number (or a switch state, or text).',
    why: 'Every knob, fader, switch and setting in your plugin is a variable underneath. No variables, no state — your plugin couldn\'t remember anything between samples.',
    studio: 'A knob remembering where you left it. The knob is the handle; the variable is the memory behind it.',
    uses: ['Every knob & fader', 'Oscillator phase', 'Filter cutoff', 'Bypass switch'],
    viz: { t: 'knobToVar', knob: 'CUTOFF', code: 'float cutoff = 1200.0f;' },
    mistake: 'Thinking a variable "does" something. It just holds the last value it was given — code elsewhere has to read it for anything to happen.',
    remember: 'Every knob you have ever moved is a number stored in a variable.',
    related: ['type', 'float', 'int', 'bool', 'memory', 'const'],
    appears: [{ z: 1, node: 'l1' }, { z: 3, label: 'parameters & APVTS' }],
    search: ['memory', 'value', 'store', 'remember', 'knob'],
  },
  {
    id: 'type', t: 'type', c: 'BASICS',
    plain: 'The kind of value a variable can hold: a decimal number, a whole number, a true/false switch. In C++ you declare the type up front, and it never changes.',
    why: 'Audio is floats, MIDI notes are whole numbers, bypass is true/false. Pick the wrong type and audio truncates to silence or notes go out of range — the compiler checks types so those mistakes fail early.',
    studio: 'The kind of jack: audio, MIDI, or footswitch. No cross-plugging — each cable type carries its own kind of signal.',
    uses: ['Samples (float)', 'MIDI notes (int)', 'Switches (bool)', 'Phase (double)'],
    mistake: 'Mixing types casually — dividing two ints and expecting a decimal result, or storing 0.73 in an int and losing everything after the point.',
    remember: 'A type says what kind of value fits in the jack.',
    related: ['variable', 'float', 'int', 'bool', 'double'],
    appears: [{ z: 1, node: 'l1' }],
    search: ['kind', 'number', 'data'],
  },
  {
    id: 'float', t: 'float', full: 'floating-point number (32-bit)', c: 'BASICS',
    plain: 'A number that can hold decimals, like 0.5 or -0.73. The standard type for audio: every sample and almost every knob value is a float. Write float values with an f on the end: 0.5f.',
    why: 'Audio samples are fractional values, normally between -1.0 and +1.0. Floats are what your DSP reads and writes, tens of thousands of times per second.',
    studio: 'A fader position: smoothly variable, any value in the range — not clicks between fixed steps.',
    uses: ['Every audio sample', 'Gain / volume', 'Cutoff & resonance', 'Mix amounts'],
    mistake: 'Forgetting the f suffix. `0.5` alone is a double (a bigger, slower cousin) that gets converted — write `0.5f` in audio code.',
    remember: 'Audio is floats: fractional numbers, usually between -1.0 and +1.0.',
    related: ['double', 'sample', 'type', 'gain', 'amplitude'],
    appears: [{ z: 1, node: 'l1' }, { z: 4, node: 'd1' }],
    search: ['volume', 'decimal', 'number', 'fraction'],
  },
  {
    id: 'double', t: 'double', full: 'double-precision floating-point (64-bit)', c: 'BASICS',
    plain: 'A float with twice the precision — it can hold many more decimal places accurately. Slower and bigger, so it\'s used where precision genuinely matters.',
    why: 'An oscillator\'s phase accumulates tiny steps for hours; in a float those errors slowly detune it. Doubles keep long-running positions accurate.',
    studio: 'The difference between a rough tape counter and a sample-accurate playhead readout.',
    uses: ['Oscillator phase', 'Sample rate values', 'Long-running counters'],
    mistake: 'Using double everywhere "to be safe" — samples stay float; doubles are for accumulating positions, not for the audio itself.',
    remember: 'double = extra decimal precision for values that accumulate over time.',
    related: ['float', 'phase', 'oscillator', 'sample-rate'],
    appears: [{ z: 1, node: 'l1' }, { z: 4, node: 'd5' }],
    search: ['precision', 'decimal'],
  },
  {
    id: 'int', t: 'int', full: 'integer', c: 'BASICS',
    plain: 'A whole number: no decimal point. Used for counting things — samples, notes, voices, slots.',
    why: 'MIDI notes are 0–127, buffers hold a whole number of samples, loops count in whole steps. And the classic trap: int ÷ int throws the remainder away (3 / 2 gives 1).',
    studio: 'A step count on a sequencer: step 7 exists, step 7.5 doesn\'t.',
    uses: ['MIDI notes (0–127)', 'Sample counts', 'Loop counters', 'Voice slots'],
    mistake: 'Dividing two ints and expecting a decimal — `50 / 100` is 0, which is how a "50% mix" knob outputs silence.',
    remember: 'ints count; they never hold fractions — and int ÷ int drops the remainder.',
    related: ['float', 'type', 'loop', 'midi'],
    appears: [{ z: 1, node: 'l1' }],
    aka: ['integer'],
    search: ['whole number', 'count'],
  },
  {
    id: 'bool', t: 'bool', full: 'boolean', c: 'BASICS',
    plain: 'A value that is only ever true or false. The type for anything that\'s on or off.',
    why: 'Bypass, mute, solo, "is this voice playing?", "is the gate open?" — plugin logic runs on true/false decisions.',
    studio: 'A footswitch: down or up. Nothing in between.',
    uses: ['Bypass switch', 'Mute / solo', 'Voice active flag', 'Sync on/off'],
    mistake: 'Comparing with `== true` (or worse, assigning with `=` in an if). For switches, just write `if (bypassed)`.',
    remember: 'bool = a footswitch: true or false, nothing else.',
    related: ['if-else', 'type', 'variable'],
    appears: [{ z: 1, node: 'l1' }, { z: 1, node: 'l4' }],
    aka: ['boolean'],
    search: ['switch', 'true', 'false', 'toggle', 'on off'],
  },
  {
    id: 'function', t: 'function', c: 'BASICS',
    plain: 'A named block of processing: values go in, one job happens, a result comes back. Define it once, use it anywhere.',
    why: 'Your gain stage, your dB converter, your envelope step — each is a function. Plugins are functions calling functions, like pedals feeding pedals.',
    studio: 'A pedal: signal and knob settings in, the circuit works, processed signal out.',
    uses: ['applyGain()', 'dbToGain()', 'nextSample()', 'processBlock()'],
    viz: { t: 'chain', nodes: ['sample in', 'applyGain()', 'sample out'], accent: 1 },
    mistake: 'Calling a function and ignoring what it returns — the signal got processed, but nothing was patched to the output.',
    remember: 'Signal in, processing inside, signal out — every function is a pedal.',
    related: ['parameter', 'return-value', 'argument', 'method'],
    appears: [{ z: 1, node: 'l3' }, { z: 1, node: 'c1' }],
    search: ['pedal', 'process', 'call'],
  },
  {
    id: 'parameter', t: 'parameter', c: 'BASICS',
    plain: 'A named input a function receives — declared in its parentheses. When you call the function, your values land in its parameters. (In plugin-land, "parameter" also means an automatable knob — see APVTS.)',
    why: 'Parameters are how you hand a function the signal and the knob settings it needs: `applyGain(float sample, float gain)` takes two.',
    studio: 'The knobs on a pedal: the settings you hand the circuit along with the signal.',
    uses: ['Function inputs', 'Plugin knobs (APVTS)', 'processBlock arguments'],
    mistake: 'Confusing parameters (the function\'s named slots) with arguments (the actual values you pass in a call).',
    remember: 'Parameters are the named input jacks of a function.',
    related: ['function', 'argument', 'apvts', 'return-value'],
    appears: [{ z: 1, node: 'l3' }, { z: 3, label: 'APVTS parameter layouts' }],
    search: ['input', 'knob'],
  },
  {
    id: 'argument', t: 'argument', c: 'BASICS',
    plain: 'The actual value you pass when calling a function. In `applyGain(0.8f, 0.5f)`, the arguments are 0.8f and 0.5f — they land in the function\'s parameters.',
    why: 'Understanding parameter (the slot) vs argument (the value) makes compiler messages readable: "no matching function" errors are almost always about argument types.',
    studio: 'The actual knob positions for this one pass — the settings, not the knobs.',
    uses: ['Every function call', 'Compiler error messages'],
    mistake: 'Passing arguments in the wrong order — C++ matches them by position, not by name.',
    remember: 'Arguments are the values; parameters are the slots they land in.',
    related: ['parameter', 'function'],
    appears: [{ z: 1, node: 'l3' }],
    search: ['value', 'pass'],
  },
  {
    id: 'return-value', t: 'return value', c: 'BASICS',
    plain: 'The single value a function hands back to whoever called it. Its type is the first word of the function\'s signature; `void` means "returns nothing."',
    why: 'A per-sample processor returns the processed sample; a dB converter returns the gain. If you ignore a return value, the work was done for nothing.',
    studio: 'The output jack: the processed signal leaving the pedal.',
    uses: ['Processed samples', 'Converted values', 'Success/failure flags'],
    mistake: 'Writing a function that computes the right value but never `return`s it — or calling one and dropping the result on the floor.',
    remember: 'return is the output jack — one value, back to the caller.',
    related: ['function', 'parameter'],
    appears: [{ z: 1, node: 'l3' }],
    search: ['output', 'result'],
  },
  {
    id: 'if-else', t: 'if / else', c: 'BASICS',
    plain: 'Code that decides: run this block only when a condition is true; otherwise run the other one. Chains of else-if pick exactly one branch.',
    why: 'Threshold logic is everywhere in audio: gates, compressors, limiters, "is this voice free?", "are we bypassed?" — all if-statements.',
    studio: 'A noise gate: above the threshold the branch opens, otherwise the else path runs.',
    uses: ['Gate / compressor thresholds', 'Bypass logic', 'Voice allocation', 'Clip protection'],
    viz: { t: 'gate' },
    mistake: 'Typing `=` (store) when you mean `==` (compare) — `if (x = 1)` silently rewrites x and always runs.',
    remember: 'A gate is just an if statement with good marketing.',
    related: ['bool', 'switch-statement', 'cutoff'],
    appears: [{ z: 1, node: 'l4' }],
    aka: ['if', 'else', 'branch', 'condition'],
    search: ['decision', 'threshold', 'gate', 'compare'],
  },
  {
    id: 'switch-statement', t: 'switch', c: 'BASICS',
    plain: 'A selector statement: one whole-number value chooses between fixed cases. Each case ends with break, or the code "falls through" into the next case.',
    why: 'Waveform selectors, filter modes, sync divisions — any fixed-position choice reads cleaner as a switch than a ladder of if/elses.',
    studio: 'A rotary selector: discrete positions, each wired to its own circuit.',
    uses: ['Waveform select', 'Filter mode (LP/HP/BP)', 'Delay sync mode', 'Reverb algorithm'],
    viz: { t: 'selector', options: ['SINE', 'SAW', 'SQUARE', 'NOISE'], active: 1 },
    mistake: 'Forgetting break — the selector leaks into the next position, and saw also triggers square.',
    remember: 'switch is a rotary selector; break is the click that stops it.',
    related: ['if-else', 'enum', 'int'],
    appears: [{ z: 1, node: 'l5' }],
    aka: ['case', 'switch case'],
    search: ['selector', 'mode', 'choose'],
  },
  {
    id: 'loop', t: 'loop', c: 'BASICS',
    plain: 'Code that repeats. A `for` loop repeats a known number of times with a counter; a `while` loop repeats until a condition turns false.',
    why: 'Audio arrives in blocks of hundreds of samples, and a loop visits each one: `for (int i = 0; i < numSamples; ++i)` is the most important line in audio programming.',
    studio: 'Rolling through a reel of tape sample by sample until the reel ends.',
    uses: ['The block loop', 'Delay line movement', 'Peak metering', 'Voice rendering'],
    viz: { t: 'buffer', n: 8, cursor: 2, highlight: 2, label: 'ONE BLOCK', caption: 'the counter i visits every slot once' },
    mistake: 'Writing `<=` and stepping one slot past the end of the buffer — undefined behavior, the click-today-crash-tomorrow bug.',
    remember: 'for (int i = 0; i < numSamples; ++i) — burn it in.',
    related: ['block', 'audio-buffer', 'array', 'undefined-behavior'],
    appears: [{ z: 1, node: 'l6' }, { z: 1, node: 'o1' }],
    aka: ['for loop', 'while loop', 'iteration'],
    search: ['repeat', 'every sample'],
  },
  {
    id: 'scope', t: 'scope', c: 'BASICS',
    plain: 'The region of code where a name exists — usually the curly braces it was born in. Step outside the braces and the variable is gone.',
    why: 'Locals dying at the closing brace is why returning a pointer to a local crashes — and why state that must survive between audio blocks lives in class members, not local variables.',
    studio: 'A talkback mic that\'s only live inside the control room. Step outside and nobody hears you.',
    uses: ['Local temp values', 'Loop counters', 'Why members exist'],
    mistake: 'Declaring state inside processBlock and wondering why it forgets everything on the next block — it died at the closing brace.',
    remember: 'Variables live between their braces; state that must survive belongs in a class member.',
    related: ['variable', 'stack', 'class', 'dangling-pointer'],
    appears: [{ z: 1, node: 'l9' }],
    search: ['lifetime', 'local'],
  },

  /* ================= C++ ================= */
  {
    id: 'class', t: 'class', c: 'C++',
    plain: 'A design that bundles data (member variables) with the behavior that operates on it (member functions). From one class you build any number of objects.',
    why: 'Your oscillator, filter, voice, and the whole plugin itself are classes. Polyphony is literally one Voice class instantiated eight times.',
    studio: 'The schematic for a synth model — the design every unit is built from.',
    uses: ['Oscillator', 'Filter', 'Voice', 'AudioProcessor'],
    viz: { t: 'blueprint', cls: 'class Filter', a: 'cutoff: 200', b: 'cutoff: 2000' },
    mistake: 'Forgetting the semicolon after the closing brace: `};` — the errors it causes land in the *next* file and make no sense.',
    remember: 'A class is the design; every object built from it lives its own life.',
    related: ['object', 'method', 'constructor', 'encapsulation', 'audioprocessor'],
    appears: [{ z: 1, node: 'l10' }, { z: 1, node: 'o2' }, { z: 3, label: 'AudioProcessor' }],
    search: ['blueprint', 'design', 'template of object'],
  },
  {
    id: 'object', t: 'object', c: 'C++',
    plain: 'One instance built from a class, holding its own copy of every member variable. Two objects from the same class are fully independent.',
    why: 'Each synth voice is an object with its own phase, envelope and filter state. Turn a knob on one and the others don\'t move.',
    studio: 'One physical unit built from the schematic — its own knobs, its own settings.',
    uses: ['Each voice', 'Each channel\'s filter', 'Each LFO'],
    mistake: 'Assuming objects share their insides. They don\'t — if state seems shared, something is miswired (usually a static or a shared pointer).',
    remember: 'An object is one unit on the desk — its knobs are its own.',
    related: ['class', 'constructor', 'method', 'voice'],
    appears: [{ z: 1, node: 'l10' }],
    aka: ['instance'],
    search: ['instance', 'unit', 'copy of class'],
  },
  {
    id: 'method', t: 'method', full: 'member function', c: 'C++',
    plain: 'A function that lives inside a class and works on that object\'s own data. Called with a dot: `filter.setCutoff(500.0f)` — or through a pointer with an arrow: `filter->setCutoff(500.0f)`.',
    why: 'Everything a plugin object does — set a frequency, render a sample, reset — is a method. JUCE hands you methods to fill in: processBlock is one.',
    studio: 'A button on one specific unit: pressing it acts on that unit, not the one next to it.',
    uses: ['osc.nextSample()', 'filter.setCutoff()', 'voice.startNote()'],
    mistake: 'Forgetting which object you\'re talking to — a method always acts on the object before the dot.',
    remember: 'A method is a button on one specific unit.',
    related: ['class', 'object', 'function'],
    appears: [{ z: 1, node: 'l10' }, { z: 1, node: 'l11' }],
    aka: ['member function'],
    search: ['dot', 'call on object'],
  },
  {
    id: 'constructor', t: 'constructor', c: 'C++',
    plain: 'The special function that runs automatically the instant an object is created. Same name as the class, no return type. Its job: start the object in a valid state.',
    why: 'Voices must wake silent, filters must wake stable, your processor must declare its parameters — all constructor work. No object should boot with random knob values.',
    studio: 'The power-on sequence: relays click, defaults load, the unit wakes ready.',
    uses: ['Voice defaults', 'Parameter setup', 'Buffer member init'],
    mistake: 'Assigning members in the body instead of the `: member(value)` initializer list — the list initializes each member exactly once, first.',
    remember: 'Objects should power on valid — the constructor makes it so.',
    related: ['class', 'destructor', 'object'],
    appears: [{ z: 1, node: 'l11' }, { z: 1, node: 'c4' }],
    search: ['init', 'power on', 'create'],
  },
  {
    id: 'encapsulation', t: 'encapsulation', c: 'C++',
    plain: 'Keeping a class\'s data private and letting outside code change it only through public functions. The functions can enforce rules, so invalid states become impossible from outside.',
    why: 'A gain member that only changes through a clamping setGain() can never be 9000. Encapsulation is how plugin classes stay trustworthy as projects grow.',
    studio: 'Panel controls hiding the circuitry: users turn the knobs you provided — they don\'t open the case and resolder.',
    uses: ['Guarded setters', 'Voice state protection', 'Parameter clamping'],
    viz: { t: 'twoLayer', top: 'public: — the front panel', topSub: 'setGain(), getGain()', bottom: 'private: — the circuitry', bottomSub: 'float gain' },
    mistake: 'Making everything public "for now" — any code anywhere can then corrupt any value, and bug hunts span the whole project instead of one class.',
    remember: 'Private data + public guarded controls = a class that can\'t be put in a bad state.',
    related: ['class', 'method', 'constructor', 'const'],
    appears: [{ z: 1, node: 'l11' }, { z: 1, node: 'b3' }],
    search: ['private', 'public', 'hide', 'protect'],
  },
  {
    id: 'destructor', t: 'destructor', c: 'C++',
    plain: 'The special function that runs automatically when an object is destroyed — written `~ClassName()`. Its job: clean up anything the object was responsible for.',
    why: 'Plugins get created and destroyed constantly as sessions load and close. Cleanup that happens automatically (see RAII in Zone 2) is what keeps them from leaking memory.',
    studio: 'The power-down sequence: outputs muted, state saved, everything released cleanly.',
    uses: ['Releasing resources', 'RAII cleanup', 'Editor teardown'],
    mistake: 'Doing cleanup manually and forgetting a path — modern C++ lets destructors and smart pointers do it for you, every time.',
    remember: 'Constructors power on; destructors power down — both automatically.',
    related: ['constructor', 'smart-pointer', 'memory'],
    appears: [{ z: 2, label: 'RAII & ownership' }],
    search: ['cleanup', 'delete', 'free'],
  },
  {
    id: 'reference', t: 'reference', c: 'C++',
    plain: 'A second name for a value that already exists — written `float&`. Not a copy: writing through either name changes the one underlying value.',
    why: 'processBlock hands you the host\'s audio buffer by reference — you edit the real audio, not a copy. Forgetting the & is the classic "my effect does nothing" bug.',
    studio: 'Patching another cable into the same signal instead of making a copy — two labels, one wire.',
    uses: ['processBlock(buffer&)', 'Per-sample processors', 'const& preset reads'],
    viz: { t: 'mult', a: 'sample', b: 'float& alias', value: '0.2f' },
    mistake: 'Dropping the & in a parameter — the function quietly processes a copy and the caller\'s audio never changes.',
    remember: 'A reference is a second label on the same signal — not a copy.',
    related: ['pointer', 'variable', 'const', 'audio-buffer'],
    appears: [{ z: 1, node: 'l8' }, { z: 3, label: 'processBlock signature' }],
    search: ['alias', 'memory', 'same value', 'no copy'],
  },
  {
    id: 'pointer', t: 'pointer', c: 'C++',
    plain: 'A variable that holds where a value lives — its address — instead of the value itself. `*` follows the address to the value; `&` takes an address. It can also hold nullptr: "points at nothing."',
    why: 'JUCE hands you pointers constantly (getWritePointer gives a float* into the audio). Mishandled pointers are the #1 reason plugins crash DAWs.',
    studio: 'Writing the rack slot number on a sticky note instead of carrying the whole synth.',
    uses: ['getWritePointer()', 'Editor references', 'Sample playheads'],
    viz: { t: 'rackPointer', code: 'float* p', note: '"rack 2, slot 5"', slot: 'OSC' },
    mistake: 'Following the note without checking it — one `if (ptr != nullptr)` is the difference between a quiet skip and crashing the session.',
    remember: 'A pointer is directions to a value — check the directions before you follow them.',
    related: ['nullptr', 'reference', 'smart-pointer', 'dangling-pointer', 'memory'],
    appears: [{ z: 1, node: 'l9' }, { z: 1, node: 'b2' }, { z: 2, label: 'smart pointers & ownership' }],
    search: ['memory', 'address', 'arrow', 'crash'],
  },
  {
    id: 'smart-pointer', t: 'smart pointer', c: 'C++',
    plain: 'A pointer that manages its own cleanup: when the last owner lets go, the object it points at is destroyed automatically. The main ones are std::unique_ptr (one owner) and std::shared_ptr (shared owners).',
    why: 'Manual new/delete is how plugins leak memory and double-free crash. Modern JUCE code owns things through unique_ptr — cleanup becomes impossible to forget.',
    studio: 'A rental system for gear: when the last person checks it back in, it goes back to the warehouse automatically.',
    uses: ['Owning the editor', 'Owning DSP modules', 'Preset storage'],
    mistake: 'Still writing raw `new`/`delete` in new code. Reach for std::make_unique first; raw owning pointers are legacy style.',
    remember: 'Smart pointers make forgetting to clean up impossible.',
    related: ['pointer', 'destructor', 'memory', 'heap'],
    appears: [{ z: 2, label: 'unique_ptr & ownership' }],
    aka: ['unique_ptr', 'shared_ptr', 'make_unique'],
    search: ['ownership', 'leak', 'delete', 'raii'],
  },
  {
    id: 'nullptr', t: 'nullptr', full: 'null pointer', c: 'C++',
    plain: 'The pointer value that means "currently pointing at nothing." Its whole purpose is to be checkable before you follow a pointer.',
    why: '"The editor doesn\'t exist yet" and "no sample is loaded" are everyday plugin situations. Code that checks for nullptr survives them; code that doesn\'t crashes the DAW.',
    studio: 'A patch note that honestly says "nothing patched here." Don\'t plug into it.',
    uses: ['Editor checks', 'Optional modules', 'Unloaded samples'],
    viz: { t: 'rackPointer', code: 'float* osc', note: 'nullptr', empty: true },
    mistake: 'Dereferencing without checking. `if (p != nullptr)` — or the shorthand `if (p)` — before every use.',
    remember: 'nullptr is checkable emptiness — always check.',
    related: ['pointer', 'undefined-behavior', 'dangling-pointer'],
    appears: [{ z: 1, node: 'l9' }],
    aka: ['null', 'NULL'],
    search: ['nothing', 'empty', 'crash', 'check'],
  },
  {
    id: 'dangling-pointer', t: 'dangling pointer', c: 'C++',
    plain: 'A pointer to memory that has already been destroyed — like the address of a local variable after its function ended. The directions still read fine; the destination is gone.',
    why: 'Returning a pointer to a local buffer, or keeping a pointer to a deleted voice, gives garbage audio or delayed crashes that are brutal to trace.',
    studio: 'A note saying "delay at rack 2, slot 5" — but the show ended and the gear was struck down hours ago.',
    uses: ['Crash post-mortems', 'Why locals can\'t be returned by address'],
    mistake: 'Returning the address of a local variable. The buffer must outlive the function — make it a class member sized in prepareToPlay.',
    remember: 'Never hand out directions to something that\'s about to be destroyed.',
    related: ['pointer', 'scope', 'stack', 'undefined-behavior'],
    appears: [{ z: 1, node: 'l9' }, { z: 1, node: 'b2' }],
    search: ['garbage', 'crash', 'freed', 'destroyed'],
  },
  {
    id: 'const', t: 'const', full: 'constant (read-only)', c: 'C++',
    plain: 'A one-word lock: a const value can be read but never rewritten. Code that tries to change it refuses to build.',
    why: 'Sample rate, tuning constants, read-only preset access — locking them means the compiler catches accidental changes before they ever reach your speakers.',
    studio: 'The locked sample rate of a rolling session: everyone reads it, nobody flips it mid-take.',
    uses: ['Sample rate', 'twoPi constants', 'const& parameters'],
    mistake: 'Leaving everything changeable "to keep it simple" — then hunting who changed a value at 2am. Lock what shouldn\'t move.',
    remember: 'If a value should never change, say so — and let the compiler stand guard.',
    related: ['constexpr', 'variable', 'reference'],
    appears: [{ z: 1, node: 'l2' }],
    search: ['lock', 'read only', 'fixed'],
  },
  {
    id: 'constexpr', t: 'constexpr', full: 'constant expression', c: 'C++',
    plain: 'const\'s stricter cousin: the value is computed and locked before the program even runs — at compile time.',
    why: 'Math constants like twoPi, table sizes, fixed voice counts — burning them in at compile time is free and documents that they can never change.',
    studio: 'A value printed on the front panel at the factory — decided before the unit ever powered on.',
    uses: ['constexpr float twoPi', 'Table sizes', 'Max voice counts'],
    mistake: 'Trying to make runtime values constexpr — the sample rate arrives while running, so it can only ever be const.',
    remember: 'constexpr locks a value before the plugin even runs.',
    related: ['const', 'float'],
    appears: [{ z: 1, node: 'l2' }],
    search: ['compile time', 'constant'],
  },
  {
    id: 'enum', t: 'enum', full: 'enumeration', c: 'C++',
    plain: 'A type with a fixed menu of named options. `enum class Waveform { sine, saw, square };` — now a variable of that type can only hold one of those three, by name.',
    why: 'Waveform selectors and filter modes as raw ints invite nonsense values like 47. An enum class makes only the real options possible, and switch statements over them get compiler-checked.',
    studio: 'The printed labels around a selector knob — the only positions that exist.',
    uses: ['Waveform select', 'Filter modes', 'Play modes', 'Plugin states'],
    mistake: 'Using plain ints for modes. `enum class` names the options and blocks invalid ones for free.',
    remember: 'An enum is the printed label ring around a selector knob.',
    related: ['switch-statement', 'type', 'int'],
    appears: [{ z: 2, label: 'enum class for selectors' }],
    aka: ['enum class', 'enumeration'],
    search: ['options', 'mode', 'choices', 'named values'],
  },
  {
    id: 'namespace', t: 'namespace', c: 'C++',
    plain: 'A named container for names, so different libraries can both have a "Filter" without colliding. `std::` is the standard library\'s namespace; `juce::` is JUCE\'s.',
    why: 'Every `std::vector` and `juce::AudioBuffer` you type is namespace syntax: library name, two colons, thing.',
    studio: 'Channel naming on a big desk: "Drums/Kick" and "Keys/Kick" coexist because the group name comes first.',
    uses: ['std::', 'juce::', 'Your own utils'],
    mistake: 'Writing `using namespace std;` in headers — it dumps every std name into every file that includes you. Type the prefix.',
    remember: 'namespace::thing = which library\'s thing you mean.',
    related: ['vector', 'juce'],
    appears: [{ z: 2, label: 'reading std:: and juce::' }],
    search: ['std', 'prefix', 'colons'],
  },
  {
    id: 'template', t: 'template', c: 'C++',
    plain: 'A recipe for code that works with any type you plug in. `std::vector<float>` is the vector template with float plugged in; `std::vector<int>` is the same recipe holding ints.',
    why: 'You mostly *use* templates (vector, clamp, JUCE\'s AudioBuffer<float>) rather than write them. Reading the angle brackets calmly is the skill.',
    studio: 'One pedal enclosure design that can be built for guitar, bass, or synth level — same design, different signal type.',
    uses: ['std::vector<float>', 'AudioBuffer<float>', 'std::clamp'],
    mistake: 'Panicking at template error messages. Read the first line and the "no known conversion" note — the rest is usually noise.',
    remember: 'Angle brackets plug a type into a reusable recipe.',
    related: ['vector', 'array', 'type'],
    appears: [{ z: 2, label: 'templates in practice' }],
    search: ['angle brackets', 'generic'],
  },
  {
    id: 'vector', t: 'std::vector', c: 'C++',
    plain: 'A row of values that can grow and shrink while the program runs. It knows its own size, and resize() sets how many slots it holds.',
    why: 'Delay lines, wavetables, working buffers — the standard resizable audio storage. One rule: size it during setup, never grow it inside the audio callback (growing may allocate).',
    studio: 'A modular case you can re-rack between sessions — but never mid-performance.',
    uses: ['Delay lines', 'Wavetables', 'Sample storage', 'Scratch buffers'],
    viz: { t: 'buffer', n: 8, label: 'std::vector<float>', caption: 'resizable — but only backstage' },
    mistake: 'push_back inside processBlock. Growth can allocate, allocation can stall, and a stalled audio thread glitches.',
    remember: 'Vectors get their size backstage (prepare), never on stage (processBlock).',
    related: ['array', 'template', 'heap', 'audio-buffer', 'real-time-audio'],
    appears: [{ z: 1, node: 'l7' }, { z: 1, node: 'c3' }],
    aka: ['std::vector'],
    search: ['resizable', 'list', 'buffer', 'storage'],
  },
  {
    id: 'array', t: 'array', c: 'C++',
    plain: 'A fixed row of same-typed values, numbered from 0. The size is set when it\'s created and never changes. (std::array is the modern fixed-size version; std::vector is the resizable one.)',
    why: 'Wavetables, filter coefficient sets, anything with a known fixed size. Zero-indexing means slot 3 is the *fourth* slot — and nothing checks your bounds but you.',
    studio: 'A hardware step sequencer: 16 slots, wired in forever.',
    uses: ['Wavetables', 'Coefficient sets', 'Fixed windows'],
    viz: { t: 'buffer', n: 4, values: ['0.1', '0.4', '0.4', '0.1'], highlight: 0, label: 'float window[4]' },
    mistake: 'Reading slot [size] — one past the end. Valid slots run 0 to size-1.',
    remember: 'Arrays are fixed slots numbered from zero — stay inside them.',
    related: ['vector', 'loop', 'undefined-behavior', 'audio-buffer'],
    appears: [{ z: 1, node: 'l7' }, { z: 1, node: 'b1' }],
    aka: ['std::array'],
    search: ['slots', 'fixed', 'row'],
  },
  {
    id: 'lambda', t: 'lambda', full: 'lambda expression (anonymous function)', c: 'C++',
    plain: 'A small function written inline, right where you need it, without a name: `[this] { repaint(); }`. Handy for "when X happens, do this."',
    why: 'JUCE UI code runs on lambdas: button clicks, slider changes, timers. `slider.onValueChange = [this] { updateFilter(); };` is everyday plugin code.',
    studio: 'A sticky note macro: "when the red light comes on, mute channel 3" — instructions left right at the spot.',
    uses: ['Button onClick', 'Slider onValueChange', 'Async callbacks'],
    mistake: 'Capturing objects that may be destroyed before the lambda runs — the UI-lifetime version of a dangling pointer.',
    remember: 'A lambda is a little unnamed function you hand to "when this happens."',
    related: ['function', 'audioprocessoreditor', 'dangling-pointer'],
    appears: [{ z: 2, label: 'lambdas & callbacks' }],
    search: ['callback', 'inline function', 'onclick'],
  },
  {
    id: 'undefined-behavior', t: 'undefined behavior', c: 'C++',
    plain: 'Code the C++ rulebook makes no promises about: reading past a buffer\'s end, following a null pointer, using destroyed memory. It might seem to work, then crash somewhere unrelated.',
    why: 'UB is why a plugin runs fine for you and crashes on stage for someone else. Bounds, null checks and initialization are the everyday defenses.',
    studio: 'A patched cable with a broken shield: works in the shop, hums at soundcheck, dies mid-show — unpredictably.',
    uses: ['Out-of-bounds reads', 'Null dereference', 'Uninitialized reads'],
    mistake: 'Believing "it runs, so it\'s correct." UB often runs — until it doesn\'t, in someone else\'s DAW.',
    remember: 'Undefined behavior isn\'t an error message — it\'s the absence of any promise at all.',
    related: ['nullptr', 'dangling-pointer', 'array', 'debugger'],
    appears: [{ z: 1, node: 'l6' }, { z: 1, node: 'l9' }, { z: 6, label: 'debugging crashes' }],
    aka: ['UB'],
    search: ['crash', 'random', 'sometimes works'],
  },
  {
    id: 'header-file', t: 'header file (.h)', c: 'C++',
    plain: 'The file that declares what a class offers — its public face — for other files to #include. Starts with #pragma once.',
    why: 'PluginProcessor.h, PluginEditor.h — every class you write or read in JUCE splits into a header (what exists) and a source file (how it works).',
    studio: 'The front-panel silkscreen: every jack and knob labeled, case closed.',
    uses: ['Class declarations', 'Shared constants', 'Public interfaces'],
    viz: { t: 'twoLayer', top: 'SineOsc.h — the front panel', topSub: 'what exists', bottom: 'SineOsc.cpp — the circuit board', bottomSub: 'how it works' },
    mistake: 'Putting big function bodies in headers early on — declarations here, definitions in the .cpp (Zone 2 covers the exceptions).',
    remember: 'Panel in the .h, circuit in the .cpp.',
    related: ['source-file', 'include', 'pragma-once', 'class'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'o3' }],
    aka: ['.h', 'header'],
    search: ['declaration', 'interface'],
  },
  {
    id: 'source-file', t: 'source file (.cpp)', c: 'C++',
    plain: 'The file with the actual function bodies for a class — the how behind the header\'s what. It includes its own header first, then defines each function with the ClassName:: prefix.',
    why: 'This is where your DSP actually lives. And if a .cpp is missing from the build, the linker greets you with "undefined reference."',
    studio: 'The circuit board inside the case — where the work happens.',
    uses: ['Function bodies', 'DSP implementations', 'Your processBlock'],
    mistake: 'Writing a body but forgetting to add the .cpp to the build (CMake) — compiles fine, fails at link.',
    remember: 'The .cpp is the circuit board behind the panel.',
    related: ['header-file', 'linker', 'cmake', 'compiler'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'e3' }],
    aka: ['.cpp', 'implementation file'],
    search: ['implementation', 'body', 'definition'],
  },
  {
    id: 'include', t: '#include', c: 'C++',
    plain: 'Pastes another file\'s contents in at build time. Quotes for your own headers (`#include "SineOsc.h"`), angle brackets for library ones (`#include <vector>`).',
    why: 'It\'s how files learn about each other\'s classes. Missing includes are among the first errors you\'ll ever read — and among the easiest to fix.',
    studio: 'Loading a channel strip preset into your session — the definitions arrive ready to use.',
    uses: ['Every file\'s top lines', 'Pulling in JUCE modules'],
    mistake: 'Angle brackets for your own headers — `<MyClass.h>` searches system paths and fails. Quotes for yours.',
    remember: 'Quotes = my files; angle brackets = library files.',
    related: ['header-file', 'pragma-once', 'compiler'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'c5' }],
    search: ['import', 'quotes', 'brackets'],
  },
  {
    id: 'pragma-once', t: '#pragma once', c: 'C++',
    plain: 'The first line of every header: "include this file at most once per build unit." Without it, a header included twice redefines its class and the build fails.',
    why: 'Headers get included from many places, often indirectly. This one line prevents an entire family of confusing duplicate-definition errors.',
    studio: 'A "already patched" tag on a cable so nobody patches the same signal twice.',
    uses: ['Line one of every header you write'],
    mistake: 'Forgetting it on a new header — works until a second file includes it, then explodes mysteriously.',
    remember: 'Every header starts with #pragma once. No exceptions in this course.',
    related: ['header-file', 'include'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'c5' }],
    aka: ['include guard'],
    search: ['guard', 'twice', 'duplicate'],
  },

  /* ================= MEMORY ================= */
  {
    id: 'memory', t: 'memory', c: 'MEMORY',
    plain: 'Where all running values live — every variable, buffer and object occupies a spot in RAM while the plugin runs. C++ gives you direct, mostly unguarded access to it.',
    why: 'Audio programming is memory-intense: buffers, delay lines, samples. Most serious plugin bugs — crashes, garbage audio — are memory handled wrong.',
    studio: 'The patchbay wall of the whole studio: every signal has a physical location.',
    uses: ['Buffers & delay lines', 'Loaded samples', 'All plugin state'],
    mistake: 'Treating memory as infinite and automatic. In C++ you own the bounds, the lifetime, and the cleanup.',
    remember: 'Every value lives somewhere — C++ makes you responsible for the somewhere.',
    related: ['stack', 'heap', 'pointer', 'ram', 'allocation'],
    appears: [{ z: 1, node: 'l9' }, { z: 2, label: 'ownership & RAII' }],
    search: ['ram', 'storage', 'where values live'],
  },
  {
    id: 'stack', t: 'stack', c: 'MEMORY',
    plain: 'Fast, automatic memory for local variables: created when a function starts, gone the instant it returns. No cleanup needed — and no survival either.',
    why: 'Locals in processBlock cost nothing to create — but they vanish per block, which is why persistent state (phase, delay lines) must live in class members instead.',
    studio: 'The mixer\'s scribble strip: quick notes for this take, wiped when the take ends.',
    uses: ['Loop counters', 'Temp values', 'Small locals'],
    viz: { t: 'twoLayer', top: 'STACK — automatic, fast', topSub: 'locals; gone at return', bottom: 'HEAP — requested, flexible', bottomSub: 'big/persistent; you manage it' },
    mistake: 'Returning a pointer to a stack local — the note outlives the value it points at.',
    remember: 'Stack memory is fast, automatic, and gone at the closing brace.',
    related: ['heap', 'scope', 'dangling-pointer', 'memory'],
    appears: [{ z: 1, node: 'l9' }, { z: 2, label: 'stack vs heap ownership' }],
    search: ['local', 'automatic', 'fast memory'],
  },
  {
    id: 'heap', t: 'heap', c: 'MEMORY',
    plain: 'The big, flexible pool of memory a program requests at runtime — where vectors grow and large buffers live. Requesting it (allocation) takes an unpredictable amount of time.',
    why: 'Sample libraries and delay lines are heap-sized. But because allocation can stall, the audio thread must never allocate — everything is requested up front in prepareToPlay.',
    studio: 'The gear warehouse: room for anything, but every checkout takes paperwork — never mid-show.',
    uses: ['Delay lines', 'Loaded samples', 'Vector growth'],
    mistake: 'Allocating in the audio callback (new, resize, push_back) — the paperwork can stall the show.',
    remember: 'The heap is roomy but slow to request — do the requesting backstage.',
    related: ['stack', 'allocation', 'vector', 'real-time-audio'],
    appears: [{ z: 1, node: 'l7' }, { z: 2, label: 'allocation-free callbacks' }],
    search: ['big memory', 'dynamic', 'allocate'],
  },
  {
    id: 'allocation', t: 'allocation', full: 'memory allocation', c: 'MEMORY',
    plain: 'Asking the system for a block of heap memory at runtime — what happens inside new, vector growth, and loading a sample. Takes an unpredictable amount of time.',
    why: 'The audio callback has a hard deadline of a few milliseconds. One slow allocation inside it and the whole DAW glitches. Rule: allocate in prepareToPlay, never in processBlock.',
    studio: 'Checkout paperwork at the gear warehouse — fine during setup, fatal mid-performance.',
    uses: ['prepareToPlay sizing', 'Sample loading', 'Why push_back is banned in callbacks'],
    mistake: 'Hidden allocations: push_back, resize, creating vectors as locals, string building — all allocate, all banned on the audio thread.',
    remember: 'Allocation is unpredictable — keep it out of the audio callback, always.',
    related: ['heap', 'vector', 'real-time-audio', 'audio-thread'],
    appears: [{ z: 1, node: 'b4' }, { z: 2, label: 'real-time-safe rules' }],
    search: ['new', 'malloc', 'resize', 'glitch'],
  },
];
