/* ============================================================
   SIGNAL DICTIONARY — part D: terms introduced by Zone 2.
   Only genuinely new concepts; existing entries are reused.
   ============================================================ */

DICT.push(
  {
    id: 'raii', t: 'RAII', full: 'Resource Acquisition Is Initialization', c: 'C++',
    plain: 'The C++ pattern behind all modern resource handling: acquire a resource in an object\'s constructor, release it in the destructor. Since destructors run automatically on every exit path, cleanup can never be forgotten.',
    why: 'Plugins are created and destroyed constantly by DAWs. RAII is why a well-written plugin can load and unload ten thousand times without leaking memory, file handles, or audio devices.',
    studio: 'The venue\'s house rule: gear checked out at load-in is automatically signed back in at close — even when the show ends early.',
    uses: ['vector freeing itself', 'unique_ptr deleting', 'File handles', 'Device locks'],
    viz: { t: 'chain', nodes: ['ctor: acquire', 'object alive', 'dtor: release'], accent: 2 },
    mistake: 'Writing manual init()/cleanup() pairs. One early return, one forgotten call — leaked. Put the pair in the constructor and destructor instead.',
    remember: 'Tie cleanup to the destructor and it becomes physics, not discipline.',
    related: ['constructor', 'destructor', 'smart-pointer', 'unique-ptr', 'scope'],
    appears: [{ z: 2, node: 'm3' }, { z: 2, node: 'mo1' }],
    aka: ['resource acquisition is initialization'],
    search: ['cleanup', 'automatic', 'leak', 'release'],
  },
  {
    id: 'unique-ptr', t: 'std::unique_ptr', full: 'unique (sole-ownership) smart pointer', c: 'C++',
    plain: 'A pointer that owns one heap object and deletes it automatically when the pointer dies. Copying is a compile error — exactly one owner can exist. Created with std::make_unique.',
    why: 'In modern plugin code this is your default owner: your processor owns its DSP modules, editor and voices through unique_ptr, and delete disappears from your vocabulary.',
    studio: 'A flight case with one name on it: hold the case, own the gear. Hand it over (move) and the responsibility goes with it.',
    uses: ['Voice pools', 'DSP module ownership', 'Owning wavetables & buffers'],
    viz: { t: 'owners', mode: 'unique' },
    mistake: 'Reaching for `new` out of habit "just for now." make_unique costs nothing extra and cannot leak.',
    remember: 'One owner, automatic delete — make_unique is the new new.',
    related: ['smart-pointer', 'raii', 'move-semantics', 'pointer'],
    appears: [{ z: 2, node: 'm4' }, { z: 2, node: 'mc1' }, { z: 2, node: 'p3' }],
    aka: ['make_unique', 'unique pointer'],
    search: ['ownership', 'auto delete', 'one owner'],
  },
  {
    id: 'move-semantics', t: 'move semantics', c: 'C++',
    plain: 'Handing an object\'s contents to a new owner instead of copying them. std::move(x) marks x as "you may pillage this"; afterward x is valid but empty. For big data (audio buffers), a move costs a pointer swap where a copy costs cloning every sample.',
    why: 'Wavetables, sample data and preset blobs transfer by move — megabytes handed over in nanoseconds. It\'s also how unique_ptr ownership legally changes hands.',
    studio: 'Handing over the hard drive instead of burning a duplicate: instant — but your hands are empty afterward.',
    uses: ['Buffer handovers', 'unique_ptr transfers', 'Preset loading'],
    viz: { t: 'moveviz' },
    mistake: 'Reading a variable after moving from it and wondering where the data went. Moved-from means valid but empty — check your hands before you read.',
    remember: 'Move hands over the drive; copy burns a duplicate. Audio-sized data moves.',
    related: ['unique-ptr', 'vector', 'reference'],
    appears: [{ z: 2, node: 'm6' }, { z: 2, node: 'mb1' }, { z: 2, node: 'p4' }],
    aka: ['std::move', 'rvalue'],
    search: ['transfer', 'hand over', 'cheap copy', 'pillage'],
  },
  {
    id: 'race-condition', t: 'race condition', c: 'AUDIO CODE',
    plain: 'Two threads touching the same data with no coordination — the result depends on which thread wins the microsecond. Races produce corruption rarely, randomly, and differently on every machine.',
    why: 'Every plugin knob is UI-thread data the audio thread needs — an uncoordinated share is a race. "Works on my machine" plus a race equals "glitches on stage."',
    studio: 'Two engineers grabbing the same fader at the same instant, no talkback. Whoever wins the grab decides the mix — differently every take.',
    uses: ['Knob values', 'Meter data', 'Preset swaps under playback'],
    viz: { t: 'lanes' },
    mistake: 'Treating the absence of glitches in testing as thread safety. Races hide at your buffer size and appear at someone else\'s.',
    remember: 'Uncoordinated shared data + two threads = timing-dependent corruption.',
    related: ['thread', 'atomic', 'mutex', 'audio-thread'],
    appears: [{ z: 2, node: 'm13' }, { z: 6, node: 'r4' }],
    aka: ['data race'],
    search: ['random bug', 'sometimes glitches', 'shared variable'],
  },
  {
    id: 'mutex', t: 'mutex', full: 'mutual exclusion lock', c: 'AUDIO CODE',
    plain: 'A lock that lets only one thread into a section of code at a time. Others wait at the door until it\'s released. Fixes races — by making threads wait.',
    why: 'The waiting is the problem: if the audio thread ever waits for the UI thread, the block misses its deadline and the audio drops out. Rule: mutexes never appear in processBlock.',
    studio: '"One person at the desk at a time" — sensible, until the live performer is the one left waiting outside the door.',
    uses: ['UI/background coordination', 'File access guards', 'Never the audio path'],
    viz: { t: 'lanes', blocked: true },
    mistake: 'Locking inside processBlock "just briefly." A contested lock is unbounded — one bad microsecond and the deadline dies audibly.',
    remember: 'Locks make threads wait — and the audio thread must never wait.',
    related: ['thread', 'race-condition', 'atomic', 'audio-thread'],
    appears: [{ z: 2, node: 'm13' }, { z: 2, node: 'mb4' }],
    aka: ['lock', 'lock_guard'],
    search: ['blocking', 'wait', 'lock'],
  },
  {
    id: 'atomic', t: 'std::atomic', c: 'AUDIO CODE',
    plain: 'A variable whose reads and writes are indivisible: no thread can ever see a half-written value. One thread store()s, another load()s — safely, and lock-free on every desktop platform you\'ll ship to (check is_always_lock_free).',
    why: 'This is how a knob value crosses from the UI over to the audio thread. Every APVTS parameter reaches your DSP as an atomic — bounded, lock-free, and safe for the deadline.',
    studio: 'A relay baton: the handoff is one indivisible gesture — you hold it or you don\'t, never half.',
    uses: ['Parameter bridges', 'Meter levels out', 'FIFO positions'],
    viz: { t: 'lanes', atomic: true },
    mistake: 'Making a value atomic and skipping the smoothing. Atomics move the value safely; the smoother makes it musical. You need both.',
    remember: 'UI stores, audio loads — the atomic handoff is how knobs reach the sound.',
    related: ['thread', 'mutex', 'race-condition', 'parameter-smoothing', 'apvts'],
    appears: [{ z: 2, node: 'm14' }, { z: 2, node: 'mc5' }, { z: 2, node: 'p5' }],
    aka: ['std::atomic<float>', 'atomics'],
    search: ['thread safe', 'lock free value', 'store load'],
  },
  {
    id: 'lock-free', t: 'lock-free', c: 'AUDIO CODE',
    plain: 'Coordinating threads without any locks — using atomics and careful structure so no thread ever waits for another. The producer/consumer FIFO (First In, First Out ring queue) is the classic shape: one thread pushes, one pops, atomic positions keep them safe.',
    why: 'The audio thread can\'t wait, ever — so everything crossing into it must be lock-free: parameters via atomics, event streams via pre-allocated FIFOs. JUCE ships AbstractFifo for exactly this.',
    studio: 'A tape loop running between two rooms: one room records onto it, the other plays from it — nobody ever knocks on the other\'s door.',
    uses: ['MIDI event queues', 'Meter taps', 'Preset handoffs'],
    viz: { t: 'fifo' },
    mistake: 'Growing the queue when it fills — growth allocates. Real-time FIFOs are pre-allocated rings: full means drop or handle, never grow.',
    remember: 'Lock-free = nobody ever waits: atomics for values, ring FIFOs for streams.',
    related: ['atomic', 'mutex', 'audio-thread', 'allocation'],
    appears: [{ z: 2, node: 'm14' }, { z: 2, node: 'mo2' }, { z: 6, node: 'r4' }],
    aka: ['fifo', 'producer consumer', 'ring buffer'],
    search: ['queue', 'no locks', 'events between threads'],
  },
  {
    id: 'optional', t: 'std::optional', c: 'C++',
    plain: 'A container for a value that might honestly not exist: an optional<int> holds an int or nothing at all. Check with has_value(), read safely with value_or(fallback). Replaces magic numbers like -1.',
    why: 'A voice between notes, a preset that failed to load, a sample slot with nothing assigned — plugins are full of legitimate "nothing" states, and optional makes them impossible to forget to handle.',
    studio: 'An insert slot that can be genuinely empty — not "occupied by silence."',
    uses: ['Voice\'s current note', 'loadPreset results', 'Unassigned slots'],
    mistake: 'Encoding "nothing" as -1 or 0 and forgetting the convention three files later. optional writes the maybe into the type.',
    remember: 'optional says "maybe a value" in the type, where it can\'t be ignored.',
    related: ['variant', 'bool', 'nullptr'],
    appears: [{ z: 2, node: 'm8' }, { z: 2, node: 'mc3' }, { z: 2, node: 'p4' }],
    aka: ['std::optional', 'maybe'],
    search: ['nothing', 'maybe', 'might not exist', 'no value'],
  },
  {
    id: 'variant', t: 'std::variant', c: 'C++',
    plain: 'A slot holding exactly one value whose type can be any one of a fixed list: variant<float, bool, int> is a float OR a bool OR an int at any moment. Ask what\'s inside with std::get_if.',
    why: 'Parameter values that may be a knob (float), a switch (bool) or a choice (int) store naturally in one variant — the shape you\'ll meet again inside parameter systems.',
    studio: 'A combo jack: one hole, several plug types, exactly one plugged at a time.',
    uses: ['Parameter values', 'Mixed-type event queues', 'Config entries'],
    mistake: 'Confusing it with a struct (which holds ALL its members at once). A variant holds exactly one occupant at a time.',
    remember: 'variant = one slot, several possible types, exactly one occupant.',
    related: ['optional', 'type', 'enum'],
    appears: [{ z: 2, node: 'm8' }, { z: 3, label: 'parameter systems' }],
    aka: ['std::variant', 'get_if'],
    search: ['one of several', 'either type', 'combo'],
  }
);
