/* ============================================================
   Glossary — C++, DSP, JUCE and tooling terms.
   Shape: { t: term, c: category, d: definition, a?: audio analogy }
   Categories: 'C++', 'DSP', 'JUCE', 'TOOLS'
   ============================================================ */

const GLOSSARY = [
  { t: 'variable', c: 'C++', d: 'A named slot that stores one value of a fixed type.', a: 'A labeled knob position — one name, one current value.' },
  { t: 'type', c: 'C++', d: 'The kind of value a variable holds (float, int, bool…). Set at declaration, never changes.', a: 'The kind of jack: audio, MIDI, or footswitch. No cross-plugging.' },
  { t: 'float', c: 'C++', d: '32-bit floating-point number. The standard type for audio samples, normally in the -1.0 to +1.0 range. Literals take an f suffix: 0.5f.' },
  { t: 'double', c: 'C++', d: '64-bit floating-point number — twice the precision of float. Used for phase accumulators and other precision-critical math.' },
  { t: 'int', c: 'C++', d: 'Whole-number type. Used for counters, indexes, and MIDI data (notes 0–127). int / int truncates the remainder.' },
  { t: 'bool', c: 'C++', d: 'true or false. The type for bypass switches and flags.' },
  { t: 'const', c: 'C++', d: 'Marks a value read-only. Any code that tries to modify it fails to compile.', a: 'The locked sample rate of a running session — nobody changes it mid-take.' },
  { t: 'constexpr', c: 'C++', d: 'Like const, but the value is computed and fixed at compile time.' },
  { t: 'function', c: 'C++', d: 'A named, reusable block of code with typed inputs (parameters) and one typed output (return value).', a: 'A pedal: signal and knob settings in, processed signal out.' },
  { t: 'parameter', c: 'C++', d: 'A typed input a function receives. The caller\'s values (arguments) are copied — or referenced — into the parameters.' },
  { t: 'return value', c: 'C++', d: 'The single value a function sends back to its caller. Type void means nothing is returned.' },
  { t: 'scope', c: 'C++', d: 'The region of code where a name is valid — usually the braces it was declared in. Locals die at the closing brace.' },
  { t: 'if / else', c: 'C++', d: 'Runs code only when a condition is true, with optional alternatives. Exactly one branch of a chain executes.', a: 'A noise gate: above threshold, open; otherwise, closed.' },
  { t: 'switch', c: 'C++', d: 'Branches on one integer-like value with fixed cases. Each case needs break, or execution falls through to the next.', a: 'A rotary mode selector — discrete positions, each wired to a circuit.' },
  { t: 'loop', c: 'C++', d: 'Repeats a block of code. for = known count; while = open-ended. The block loop for(i = 0; i < numSamples; ++i) is the heart of DSP code.' },
  { t: 'array', c: 'C++', d: 'A fixed-length row of same-typed values, indexed from 0. No bounds checking — stay inside 0…size-1.' },
  { t: 'std::vector', c: 'C++', d: 'A resizable array that knows its size. resize() in setup code; never grow it inside the audio callback (it may allocate).', a: 'A delay line whose length you set while the session is stopped.' },
  { t: 'reference', c: 'C++', d: 'An alias — a second name for an existing value (float&). No copy; writes through it change the original. Must be initialized, can\'t be re-seated.', a: 'A patchbay mult: the same signal at two jack labels.' },
  { t: 'pointer', c: 'C++', d: 'A variable holding a memory address (float*). * dereferences (follows) it; & takes an address. Can be nullptr — check before dereferencing.', a: 'A written-down patch location: "delay at rack 2, slot 5".' },
  { t: 'nullptr', c: 'C++', d: 'The pointer value meaning "points at nothing". Dereferencing it is undefined behavior — typically a crash.', a: 'A note that says "nothing patched here". Don\'t plug into it.' },
  { t: 'dangling pointer', c: 'C++', d: 'A pointer to memory that has been destroyed — like the address of a local variable after its function returned. Using it is undefined behavior.' },
  { t: 'undefined behavior', c: 'C++', d: 'Code the C++ standard makes no promises about (out-of-bounds reads, null dereference, data races). May appear to work, then crash elsewhere. UB is never acceptable.' },
  { t: 'class', c: 'C++', d: 'A user-defined type bundling data (members) with functions that operate on it.', a: 'A synth schematic — the design every unit is built from.' },
  { t: 'object', c: 'C++', d: 'One instance created from a class, with its own copy of all member variables.', a: 'One physical unit on your desk. Two units, two independent sets of knobs.' },
  { t: 'constructor', c: 'C++', d: 'The function that runs automatically when an object is created, ensuring it starts in a valid state. Same name as the class, no return type.', a: 'A hardware power-on sequence: defaults loaded, unit ready.' },
  { t: 'member initializer list', c: 'C++', d: 'The : member(value) list after a constructor\'s parameters — initializes members directly, before the body runs. Preferred over assigning in the body.' },
  { t: 'encapsulation', c: 'C++', d: 'Keeping state private and exposing controlled public functions, so invalid states become impossible from outside.', a: 'Panel controls hide the circuitry — users turn knobs, they don\'t resolder.' },
  { t: 'public / private', c: 'C++', d: 'Access specifiers. public members are usable from outside code; private members only from the class\'s own functions.' },
  { t: 'header file (.h)', c: 'C++', d: 'Declares a class\'s interface for other files to #include. Starts with #pragma once.', a: 'The front-panel silkscreen: every jack labeled, case closed.' },
  { t: 'implementation file (.cpp)', c: 'C++', d: 'Defines the function bodies declared in the header, using the ClassName:: prefix.' },
  { t: '#include', c: 'C++', d: 'Pastes another file\'s contents in at compile time. Quotes ("MyClass.h") for your headers; angle brackets (<vector>) for system/library ones.' },
  { t: '#pragma once', c: 'C++', d: 'Header guard: ensures a header is included at most once per compiled file, preventing duplicate-definition errors.' },
  { t: 'compiler error', c: 'C++', d: 'A per-file build failure: syntax, types, unknown names. Points at file and line — though often one line after the real cause. Fix the first error first.' },
  { t: 'linker error', c: 'C++', d: '"undefined reference": a function was declared but no compiled body exists — never written, or its .cpp isn\'t in the build.' },
  { t: 'stack / heap', c: 'C++', d: 'Stack: fast, automatic memory for locals, freed at scope end. Heap: manually managed memory (new, vector growth) with unpredictable allocation time — which is why the audio thread avoids it.' },
  { t: 'allocation', c: 'C++', d: 'Requesting heap memory at runtime. Unbounded worst-case time; forbidden inside the audio callback. Allocate in prepareToPlay instead.' },

  { t: 'sample', c: 'DSP', d: 'One measurement of a waveform\'s amplitude at one instant — in code, one float, usually within -1.0…+1.0.' },
  { t: 'sample rate', c: 'DSP', d: 'Samples per second (44100, 48000…). Converts between time and sample counts: one second at 48 kHz is 48000 samples.' },
  { t: 'buffer / block', c: 'DSP', d: 'The chunk of samples a host delivers per callback (32–2048 samples). Smaller = lower latency, more CPU overhead.' },
  { t: 'gain', c: 'DSP', d: 'A multiplier applied to a signal. 1.0 = unity, 0.5 ≈ -6 dB, 2.0 ≈ +6 dB. Applied by multiplication, never addition.' },
  { t: 'decibel (dB)', c: 'DSP', d: 'Logarithmic level scale matching how we hear. Amplitude: gain = 10^(dB/20). 0 dB = unity; -6 dB ≈ half amplitude.' },
  { t: 'phase', c: 'DSP', d: 'Position within a waveform\'s cycle, 0 to 2π radians. An oscillator advances phase by 2π·f/fs per sample and wraps it past 2π.' },
  { t: 'DC offset', c: 'DSP', d: 'A constant added to a signal, shifting the waveform off center — wastes headroom and thumps on start/stop. One reason gain multiplies instead of adds.' },
  { t: 'audio callback', c: 'DSP', d: 'The function the host calls repeatedly with each new block, on a high-priority thread with a hard deadline. Miss the deadline and the audio glitches.', a: 'The DAW asking, every few milliseconds without fail: "next block, now."' },
  { t: 'real-time safety', c: 'DSP', d: 'Writing callback code whose worst-case time is bounded: no allocation, file access, blocking locks, logging, or unbounded loops on the audio thread.' },

  { t: 'JUCE', c: 'JUCE', d: 'The dominant C++ framework for audio plugins: one codebase building VST3, AU, AAX and standalone apps. Zone 3 onward lives here.' },
  { t: 'AudioProcessor', c: 'JUCE', d: 'The JUCE base class your plugin inherits: the host talks to your plugin entirely through its interface (prepareToPlay, processBlock, state calls).' },
  { t: 'processBlock', c: 'JUCE', d: 'The JUCE audio callback: receives an AudioBuffer and MidiBuffer, must fill/modify the audio in place under real-time rules.' },
  { t: 'prepareToPlay', c: 'JUCE', d: 'Called before playback starts, with sample rate and max block size. The place to size buffers and reset state — allocation is allowed here.' },
  { t: 'APVTS', c: 'JUCE', d: 'AudioProcessorValueTreeState: JUCE\'s parameter system — declares plugin parameters, syncs them with the host, and saves/restores state.', a: 'The preset system: every knob declared, automatable, and recallable.' },
  { t: 'VST3', c: 'JUCE', d: 'Steinberg\'s plugin format — the standard target on Windows and common everywhere. JUCE generates it from your AudioProcessor.' },

  { t: 'CMake', c: 'TOOLS', d: 'The build-system generator used for modern JUCE projects: CMakeLists.txt declares targets, sources and formats; CMake produces the platform build.' },
  { t: 'Git', c: 'TOOLS', d: 'Version control: snapshots (commits) of your codebase you can branch, compare and roll back.', a: 'Infinite undo plus takes and comps — for code.' },
  { t: 'debugger', c: 'TOOLS', d: 'A tool that pauses a running program at breakpoints so you can inspect variables and step line by line — the fastest route to understanding a crash.' },
  { t: 'DAW validation', c: 'TOOLS', d: 'Host-side checks a plugin must pass to load (e.g. Logic\'s auval). Professional plugins are tested across hosts before release.' },
];
