/* ============================================================
   SIGNAL DICTIONARY — part B: Audio Code, DSP, Synths, Math,
   Audio Engineering. Appended to DICT from part A.
   ============================================================ */

DICT.push(

  /* ================= AUDIO CODE ================= */
  {
    id: 'thread', t: 'thread', c: 'AUDIO CODE',
    plain: 'One independent lane of running code. A program can run several threads at once — and a plugin always does: at minimum, one drawing the interface and one processing audio.',
    why: 'The audio thread and UI thread touch the same knobs at the same time. Coordinating them safely is a defining skill of plugin development (Zone 6).',
    studio: 'Two engineers working the same session at once — one on the desk, one on the patch bay. Great, until they grab the same cable.',
    uses: ['Audio processing', 'UI drawing', 'Sample loading in background'],
    mistake: 'Sharing plain variables between threads and hoping. Zone 2\'s std::atomic and Zone 6\'s lock-free patterns are the real tools.',
    remember: 'A plugin is always at least two lanes of code running at once.',
    related: ['audio-thread', 'ui-thread', 'real-time-audio'],
    appears: [{ z: 2, label: 'std::atomic' }, { z: 6, label: 'lock-free communication' }],
    search: ['parallel', 'concurrent', 'lanes'],
  },
  {
    id: 'audio-thread', t: 'audio thread', c: 'AUDIO CODE',
    plain: 'The high-priority thread where the host calls your processBlock. It has a hard deadline: deliver the next block in a few milliseconds, every time, or the audio glitches.',
    why: 'Everything real-time-safe programming is about happens here: no allocation, no file access, no locks, no logging — nothing with unpredictable timing.',
    studio: 'The live performer: the show clock never stops, and nobody hands the performer paperwork mid-song.',
    uses: ['processBlock', 'All your DSP', 'MIDI event handling'],
    viz: { t: 'chain', nodes: ['DAW asks', 'processBlock()', 'audio out'], accent: 1, caption: 'a hard deadline, hundreds of times per second' },
    mistake: 'Doing "just one quick" file read or allocation on it. One stall = one audible glitch, every time it happens.',
    remember: 'The audio thread has a deadline that never, ever moves.',
    related: ['real-time-audio', 'ui-thread', 'processblock', 'allocation'],
    appears: [{ z: 1, node: 'b4' }, { z: 2, label: 'real-time rules' }, { z: 6, label: 'thread safety' }],
    search: ['callback', 'deadline', 'glitch', 'realtime'],
  },
  {
    id: 'ui-thread', t: 'UI thread', full: 'user interface (message) thread', c: 'AUDIO CODE',
    plain: 'The thread that draws your plugin\'s window and responds to clicks and knob drags. In JUCE it\'s called the message thread.',
    why: 'It\'s allowed to be slow — repainting, loading files, logging all belong here, never on the audio thread. Knowing which thread you\'re on decides what code is legal.',
    studio: 'The front-of-house engineer: important, but the show doesn\'t stop if they take a second to sip coffee.',
    uses: ['Editor painting', 'Knob interaction', 'File browsers', 'Meters (reading)'],
    mistake: 'Touching audio state directly from UI code (or vice versa) — that\'s a data race. Parameters flow through APVTS instead.',
    remember: 'Slow work lives on the UI thread — the audio thread never waits for it.',
    related: ['audio-thread', 'thread', 'audioprocessoreditor', 'apvts'],
    appears: [{ z: 3, label: 'editor basics' }, { z: 6, label: 'UI-thread safety' }],
    aka: ['message thread'],
    search: ['gui', 'interface', 'clicks', 'painting'],
  },
  {
    id: 'real-time-audio', t: 'real-time audio', c: 'AUDIO CODE',
    plain: 'Audio produced live, block by block, against a deadline — as opposed to rendering a file offline. Miss one deadline and the listener hears a glitch.',
    why: 'Real-time safety is the discipline that separates plugins that glitch from plugins that ship: bounded work only, on the audio thread, every block.',
    studio: 'Live performance vs. studio overdubs: on stage there are no second takes.',
    uses: ['All plugin DSP', 'Why callbacks have rules', 'Buffer size tradeoffs'],
    mistake: 'Testing only in ideal conditions. Real-time bugs appear under load — many tracks, small buffers, slow disks.',
    remember: 'Real-time means the deadline is part of the spec.',
    related: ['audio-thread', 'latency', 'buffer-size', 'allocation'],
    appears: [{ z: 2, label: 'real-time-safe principles' }, { z: 6, label: 'deterministic behavior' }],
    aka: ['realtime', 'real time'],
    search: ['live', 'deadline', 'glitch', 'dropout'],
  },
  {
    id: 'audio-callback', t: 'audio callback', c: 'AUDIO CODE',
    plain: 'The function the host calls over and over — "here\'s the next block, process it, now." In JUCE, that function is processBlock. You never call it; the host does.',
    why: 'This inversion — the DAW calls *you* — is the mental model behind all plugin code. Your DSP lives inside a function someone else fires hundreds of times a second.',
    studio: 'The tape op handing you one reel at a time, on a fixed clock: "next reel. next reel. next reel."',
    uses: ['processBlock', 'Standalone audio apps', 'The whole DSP lifecycle'],
    viz: { t: 'chain', nodes: ['HOST', 'your callback', 'speakers'], accent: 1, caption: 'the host calls you — hundreds of times per second' },
    mistake: 'Trying to "run" your own audio loop. Plugins don\'t run — they respond, block by block.',
    remember: 'You don\'t call the DAW — the DAW calls you.',
    related: ['processblock', 'audio-thread', 'block', 'host'],
    appears: [{ z: 1, node: 'c6' }, { z: 3, label: 'processBlock' }],
    aka: ['callback'],
    search: ['processblock', 'called', 'next block'],
  },
  {
    id: 'audio-buffer', t: 'audio buffer', c: 'AUDIO CODE',
    plain: 'The container of samples handed to your plugin each callback: one row of floats per channel, a few hundred samples long. You read it, process it, and write the result back in place.',
    why: 'Every effect you ever write edits this buffer. JUCE\'s AudioBuffer gives you getWritePointer(channel) — a float* straight into the audio.',
    studio: 'A tray carrying the next small chunk of audio to your speakers — refill it before it leaves.',
    uses: ['processBlock argument', 'In-place effects', 'Metering'],
    viz: { t: 'buffer', n: 8, cursor: 2, highlight: 2, label: 'ONE CHANNEL OF THE BUFFER' },
    mistake: 'Confusing the audio buffer (this block\'s samples) with your own storage buffers (delay lines etc.) — same word, different jobs.',
    remember: 'The audio buffer is the tray of samples you must refill every callback.',
    related: ['block', 'sample', 'vector', 'processblock', 'reference'],
    appears: [{ z: 1, node: 'l6' }, { z: 3, label: 'AudioBuffer & channels' }],
    aka: ['AudioBuffer', 'buffer'],
    search: ['tray', 'samples', 'channel data'],
  },
  {
    id: 'block', t: 'block', c: 'AUDIO CODE',
    plain: 'One chunk of samples processed in a single callback — typically 32 to 2048 samples. The DAW hands blocks to your plugin one after another, seamlessly.',
    why: 'Everything you compute per-block (like reading a knob once) vs per-sample (like advancing an oscillator) is an engineering decision you\'ll make constantly.',
    studio: 'One reel in the endless relay of reels the tape op hands you.',
    uses: ['processBlock unit of work', 'Parameter update timing', 'Metering windows'],
    mistake: 'Assuming a fixed block size. Hosts change it — your code must handle any size up to the maximum given in prepareToPlay.',
    remember: 'Audio flows as an endless relay of blocks — never assume their size.',
    related: ['audio-buffer', 'buffer-size', 'audio-callback', 'sample'],
    appears: [{ z: 1, node: 'l6' }, { z: 3, label: 'prepareToPlay & block sizes' }],
    search: ['chunk', 'samples at once'],
  },
  {
    id: 'sample', t: 'sample', c: 'AUDIO CODE',
    plain: 'One measurement of a waveform\'s height at one instant — in code, one float, normally between -1.0 and +1.0. Tens of thousands per second make up what you hear. (In sampler-land, "a sample" also means a whole recorded clip.)',
    why: 'The atom of digital audio. Every DSP algorithm is ultimately "do math on each sample."',
    studio: 'One dot on the waveform display, zoomed all the way in.',
    uses: ['All DSP math', 'Buffers', 'Metering'],
    viz: { t: 'wave', type: 'samples' },
    mistake: 'Forgetting samples routinely exceed ±1.0 inside float processing chains — only the converters at the very end truly clip.',
    remember: 'A sample is one float: the waveform\'s height at one instant.',
    related: ['sample-rate', 'float', 'audio-buffer', 'waveform'],
    appears: [{ z: 1, node: 'l1' }, { z: 4, label: 'sample-level DSP' }],
    search: ['dot', 'measurement', 'value'],
  },
  {
    id: 'sample-rate', t: 'sample rate', c: 'AUDIO CODE',
    plain: 'How many samples represent one second of audio — 44100 or 48000 in most sessions. It converts between time and sample counts: at 48 kHz, one second is 48,000 samples.',
    why: 'Every time-based DSP value depends on it: a 500 ms delay is sampleRate/2 samples; an oscillator\'s step size is 2π·freq/sampleRate. Your plugin learns it in prepareToPlay.',
    studio: 'The session\'s frame rate for audio — the grid everything time-based is measured against.',
    uses: ['Delay times', 'Oscillator increments', 'Envelope rates', 'prepareToPlay'],
    mistake: 'Hard-coding 44100. Sessions run at 48k, 96k, 192k — always use the rate the host gives you.',
    remember: 'Never hard-code the sample rate — the host tells you in prepareToPlay.',
    related: ['sample', 'buffer-size', 'preparetoplay', 'frequency'],
    appears: [{ z: 1, node: 'l2' }, { z: 4, label: 'sample rate & time' }],
    aka: ['fs', '44100', '48000'],
    search: ['48k', '44.1', 'hz', 'per second'],
  },
  {
    id: 'buffer-size', t: 'buffer size', c: 'AUDIO CODE',
    plain: 'How many samples the host processes per callback — the setting you\'ve changed in your DAW\'s audio preferences a hundred times. Small = responsive but CPU-hungry; large = efficient but laggy.',
    why: 'It sets your plugin\'s deadline: at 48 kHz and 128 samples, processBlock must finish in under 2.7 ms — every single time.',
    studio: 'The tray size: small trays arrive constantly (low latency, more trips); big trays arrive rarely (efficient, but slower to react).',
    uses: ['Latency tradeoff', 'The callback deadline', 'prepareToPlay maximum'],
    mistake: 'Assuming it\'s constant — hosts can change it between callbacks. Handle any size up to the stated maximum.',
    remember: 'Buffer size sets the deadline your DSP must always beat.',
    related: ['latency', 'block', 'sample-rate', 'audio-thread'],
    appears: [{ z: 3, label: 'prepareToPlay' }, { z: 4, label: 'buffer size tradeoffs' }],
    search: ['128', '256', '512', 'latency setting'],
  },
  {
    id: 'latency', t: 'latency', c: 'AUDIO CODE',
    plain: 'The delay between cause and result — pressing a key and hearing the note. In digital audio it\'s mostly buffering: samples wait in trays before reaching your ears.',
    why: 'Producers feel latency instantly. Some DSP (lookahead limiting, oversampling) adds its own — pro plugins report it to the host so the DAW can compensate.',
    studio: 'The gap between hitting the pad and hearing the kick — the thing you\'ve fought in every tracking session.',
    uses: ['Buffer size choice', 'Lookahead processing', 'Plugin delay compensation'],
    mistake: 'Adding processing latency and not reporting it — everything the plugin touches lands late in the mix.',
    remember: 'Latency is buffering; if your DSP adds any, report it to the host.',
    related: ['buffer-size', 'block', 'oversampling'],
    appears: [{ z: 4, label: 'buffer size & latency' }, { z: 6, label: 'plugin delay compensation' }],
    search: ['delay', 'lag', 'slow response'],
  },
  {
    id: 'denormals', t: 'denormal numbers', c: 'AUDIO CODE',
    plain: 'Absurdly tiny float values (like 10⁻³⁸) that CPUs process far slower than normal numbers. Audio tails fading toward silence drift into this range.',
    why: 'A reverb tail decays, values go denormal, CPU use spikes 10–100× on "silence." The fix: flush-to-zero mode or adding tiny offsets — standard practice in every pro plugin.',
    studio: 'A fader so close to -∞ the desk starts stuttering trying to compute it.',
    uses: ['Reverb/delay tails', 'Filter feedback paths', 'CPU spike hunts'],
    mistake: 'Profiling with test tones only. Denormal spikes appear on decaying tails and silence — exactly what tone tests never show.',
    remember: 'Near-silence can cost more CPU than sound — flush denormals to zero.',
    related: ['float', 'cpu', 'filter'],
    appears: [{ z: 4, label: 'denormals & DC offset' }],
    aka: ['subnormal', 'denormal'],
    search: ['cpu spike', 'tiny numbers', 'silence slow'],
  },
  {
    id: 'parameter-smoothing', t: 'parameter smoothing', c: 'AUDIO CODE',
    plain: 'Gliding a parameter from its old value to its new one over a few milliseconds instead of jumping instantly. Sudden jumps in gain or cutoff create audible clicks.',
    why: 'The difference between a plugin that zippers and clicks under automation and one that feels expensive. Every continuous parameter in a shipping plugin is smoothed.',
    studio: 'A motorized fader glides to its new position — it doesn\'t teleport.',
    uses: ['Gain changes', 'Filter sweeps', 'Any automated knob'],
    mistake: 'Applying the raw target value per block. Smooth toward the target per sample (JUCE\'s SmoothedValue does exactly this).',
    remember: 'Parameters glide; they never teleport.',
    related: ['automation', 'gain', 'apvts', 'dc-offset'],
    appears: [{ z: 4, label: 'gain & parameter smoothing' }],
    aka: ['smoothing', 'SmoothedValue'],
    search: ['click', 'zipper', 'glide', 'jump'],
  },

  /* ================= DSP / MATH ================= */
  {
    id: 'dsp', t: 'DSP', full: 'Digital Signal Processing', c: 'DSP',
    plain: 'Doing math on audio numbers to change the sound. Every effect and synth voice is DSP: multiply for gain, delay-and-mix for echo, feedback math for filters.',
    why: 'DSP is the "what your plugin actually does" layer — everything else (UI, parameters, formats) exists to host it.',
    studio: 'The circuitry of every pedal and rack unit you own — expressed as arithmetic.',
    uses: ['Gain & mixing', 'Filters & EQs', 'Delays & reverbs', 'Synthesis'],
    viz: { t: 'chain', nodes: ['input', 'math', 'output'], accent: 1, caption: 'effects are arithmetic applied to samples' },
    mistake: 'Thinking DSP requires heavy math to start. Gain is one multiply; a delay is an array and an index. Depth comes gradually.',
    remember: 'DSP is math on samples — starting with a single multiply.',
    related: ['sample', 'gain', 'filter', 'oscillator'],
    appears: [{ z: 1, node: 'p1' }, { z: 4, label: 'the DSP workshop' }],
    search: ['digital signal processing', 'effects math', 'processing'],
  },
  {
    id: 'gain', t: 'gain', c: 'DSP',
    plain: 'A multiplier applied to a signal: 1.0 leaves it alone, 0.5 halves it (≈ -6 dB), 2.0 doubles it (≈ +6 dB), 0.0 silences it. Applied by multiplication, never addition.',
    why: 'The first DSP you\'ll ever write — `sample * gain` — and a stage of nearly every effect thereafter (dry/wet, feedback, envelopes are all gains).',
    studio: 'Every fader and trim knob you\'ve ever touched.',
    uses: ['Volume controls', 'Dry/wet mixing', 'Feedback amounts', 'Velocity scaling'],
    mistake: 'Adding instead of multiplying — addition shifts the waveform off center (DC offset) instead of making it louder.',
    remember: 'Gain multiplies. 1.0 is unity; 0.5 is about -6 dB.',
    related: ['decibel', 'amplitude', 'float', 'parameter-smoothing'],
    appears: [{ z: 1, node: 'c1' }, { z: 1, node: 'p1' }, { z: 7, label: 'the gain plugin' }],
    search: ['volume', 'level', 'louder', 'multiply'],
  },
  {
    id: 'decibel', t: 'decibel (dB)', c: 'MATH',
    plain: 'The logarithmic loudness scale that matches how ears actually hear. For amplitude: gain = 10^(dB/20). Landmarks: 0 dB = unchanged, -6 dB ≈ half, +6 dB ≈ double, -∞ = silence.',
    why: 'Users think in dB; DSP multiplies by linear gain. The conversion between them appears in virtually every plugin you\'ll build.',
    studio: 'The numbers printed on every fader you\'ve ever mixed with.',
    uses: ['Gain knobs', 'Meters', 'Threshold controls', 'Fader laws'],
    mistake: 'Using /10 in the formula — that\'s the power version. Amplitude (what faders control) uses /20: check that -6 dB gives ≈0.5.',
    remember: 'gain = 10^(dB/20) — and -6 dB is half.',
    related: ['gain', 'amplitude', 'float'],
    appears: [{ z: 1, node: 'c1' }, { z: 1, node: 'p1' }],
    aka: ['dB'],
    search: ['loudness', 'volume scale', 'fader numbers'],
  },
  {
    id: 'dc-offset', t: 'DC offset', full: 'direct-current offset', c: 'DSP',
    plain: 'A constant value added to a signal, shifting the whole waveform off its center line. It carries no sound but eats headroom and thumps on start/stop.',
    why: 'It\'s why gain multiplies instead of adds, and why some algorithms (rectification, certain distortions) need a DC-blocking filter after them.',
    studio: 'A waveform sitting above the center line in your editor — the classic "remove DC offset" fix.',
    uses: ['Why gain multiplies', 'Post-distortion cleanup', 'Metering accuracy'],
    mistake: 'Adding a constant to "warm up" a signal — you\'ve added inaudible offset, not warmth, and lost headroom doing it.',
    remember: 'Audio lives centered on zero — adding constants shifts it, gain multiplies it.',
    related: ['gain', 'waveform', 'filter'],
    appears: [{ z: 4, label: 'DC offset & blocking' }],
    search: ['offset', 'center line', 'shifted waveform'],
  },
  {
    id: 'waveform', t: 'waveform', c: 'DSP',
    plain: 'The shape a signal traces over time — sine (pure), saw (bright, buzzy), square (hollow), noise (all frequencies at once). The shape determines the harmonic content you hear.',
    why: 'Oscillators generate waveforms; effects reshape them. "Which waveform" is the first sound-design decision of any synth patch — and a switch statement in code.',
    studio: 'The shapes on your synth\'s OSC section, and the picture in every audio editor.',
    uses: ['Oscillator shapes', 'LFO shapes', 'Waveshaping targets'],
    viz: { t: 'wave', type: 'saw', caption: 'a sawtooth — bright, every harmonic present' },
    mistake: 'Generating naive digital saws/squares at audio rate — their sharp edges alias. Zone 4 covers band-limited versions.',
    remember: 'The waveform\'s shape is its harmonic recipe.',
    related: ['oscillator', 'sample', 'aliasing', 'lfo'],
    appears: [{ z: 1, node: 'l5' }, { z: 4, label: 'oscillators & shapes' }],
    search: ['shape', 'sine', 'saw', 'square'],
  },
  {
    id: 'oscillator', t: 'oscillator', c: 'SYNTHS',
    plain: 'The sound source of a synth: it generates a repeating waveform at a chosen frequency. In code, it advances a phase position each sample and outputs the wave\'s value at that position.',
    why: 'You\'ll build one in Zone 1\'s final mission — phase, increment, wrap, output. Every synth you make afterward is oscillators plus shaping.',
    studio: 'The OSC section — where sound begins before filters and envelopes shape it.',
    uses: ['Synth voices', 'LFOs (slow oscillators)', 'Test tones', 'FM operators'],
    viz: { t: 'wave', type: 'sine', caption: 'phase sweeps 0 → 2π, tracing the cycle' },
    mistake: 'Resetting phase to 0 when it passes 2π instead of subtracting 2π — the lost fraction detunes the pitch.',
    remember: 'An oscillator is a phase that advances and wraps, tracing a shape.',
    related: ['phase', 'frequency', 'waveform', 'lfo', 'voice'],
    appears: [{ z: 1, node: 'p2' }, { z: 4, label: 'band-limited oscillators' }, { z: 5, label: 'unison & detune' }],
    aka: ['osc'],
    search: ['sound source', 'tone', 'generator'],
  },
  {
    id: 'frequency', t: 'frequency', c: 'DSP',
    plain: 'How many times per second something repeats, measured in Hertz (Hz). For audio: pitch. A440 means the waveform completes 440 cycles every second.',
    why: 'Oscillator pitch, filter cutoff, LFO rate — three knobs, one unit. Converting MIDI notes to Hz (A440 × 2^((note-69)/12)) is a synth rite of passage.',
    studio: 'Pitch — and also the Hz numbers on your EQ.',
    uses: ['Oscillator pitch', 'Filter cutoff', 'LFO rate', 'EQ bands'],
    mistake: 'Confusing frequency (cycles per second) with sample rate (samples per second) — related grids, different things.',
    remember: 'Frequency is repeats-per-second: pitch for oscillators, position for EQs.',
    related: ['phase', 'sample-rate', 'oscillator', 'cutoff'],
    appears: [{ z: 1, node: 'p2' }, { z: 4, label: 'frequency & pitch math' }],
    aka: ['hz', 'hertz', 'pitch'],
    search: ['pitch', 'note', 'hz', 'cycles'],
  },
  {
    id: 'amplitude', t: 'amplitude', c: 'DSP',
    plain: 'The height of a waveform — how far samples swing from zero. Bigger swings, louder sound. Gain scales amplitude; dB measures it.',
    why: 'Amplitude is what your meters read, what compressors act on, and what every gain stage changes.',
    studio: 'How tall the waveform is in your editor — the loudness dimension.',
    uses: ['Metering', 'Compression', 'Envelopes (amplitude over time)'],
    mistake: 'Equating amplitude with perceived loudness — perception is logarithmic (dB) and frequency-dependent.',
    remember: 'Amplitude is the height of the swing; gain is what scales it.',
    related: ['gain', 'decibel', 'envelope', 'sample'],
    appears: [{ z: 4, label: 'amplitude & envelopes' }],
    search: ['height', 'loudness', 'level'],
  },
  {
    id: 'phase', t: 'phase', c: 'DSP',
    plain: 'Position within a waveform\'s cycle, running 0 to 2π (then wrapping). An oscillator is nothing but a phase that advances by 2π·freq/sampleRate each sample.',
    why: 'Phase is the state an oscillator carries between samples. Get its bookkeeping right (advance, wrap, keep precision) and synthesis works; get it wrong and pitch drifts.',
    studio: 'Where in its cycle the wave currently is — what you\'re really adjusting when you time-align multi-mic\'d drums. (The \u2205 button on a DI is polarity inversion, often mislabeled "phase.")',
    uses: ['Oscillator state', 'Phase cancellation', 'Stereo wideners', 'FM synthesis'],
    mistake: 'Storing phase in a float that accumulates for hours — precision drifts. Use double for accumulators.',
    remember: 'Phase is the oscillator\'s bookmark: advance it, wrap it, keep it precise.',
    related: ['oscillator', 'frequency', 'double', 'sample-rate'],
    appears: [{ z: 1, node: 'p2' }, { z: 4, label: 'phase & interpolation' }],
    search: ['cycle position', 'cancellation', '2pi'],
  },
  {
    id: 'envelope', t: 'envelope', c: 'SYNTHS',
    plain: 'A control shape that changes a value over time — most famously ADSR: Attack (rise), Decay (fall), Sustain (hold level), Release (fade after key-up). Applied to amplitude, it turns raw tone into a note.',
    why: 'Envelopes are why a synth note has life instead of being an unbroken drone. You\'ll implement one as a small state machine in Zone 4.',
    studio: 'The ADSR knobs on every synth you own.',
    uses: ['Amplitude shaping', 'Filter sweeps per note', 'Pitch blips', 'Sidechain-style ducking'],
    viz: { t: 'adsr' },
    mistake: 'Jumping levels instantly at stage changes — envelopes glide between stages, or they click.',
    remember: 'An envelope is a value with a life cycle: rise, fall, hold, fade.',
    related: ['attack', 'decay', 'sustain', 'release', 'amplitude', 'voice'],
    appears: [{ z: 4, label: 'envelope state machines' }, { z: 5, label: 'per-voice envelopes' }],
    aka: ['ADSR', 'eg', 'envelope generator'],
    search: ['adsr', 'shape over time', 'note shape'],
  },
  {
    id: 'attack', t: 'attack', c: 'SYNTHS',
    plain: 'The first envelope stage: how long the value takes to rise from zero to full when the note starts. Short attack = instant hit; long attack = swell.',
    why: 'Attack time is the difference between a pluck and a pad. In code it sets the per-sample rise rate of your envelope\'s first stage.',
    studio: 'The knob that turns a stab into a swell.',
    uses: ['Amp envelopes', 'Filter envelopes', 'Transient design', 'Compressor timing'],
    mistake: 'A 0 ms attack straight to full level clicks — even "instant" attacks ramp over a millisecond or two.',
    remember: 'Attack is the rise; even instant needs a tiny ramp.',
    related: ['envelope', 'decay', 'sustain', 'release'],
    appears: [{ z: 4, label: 'envelope stages' }],
    search: ['rise', 'start', 'pluck', 'swell'],
  },
  {
    id: 'decay', t: 'decay', c: 'SYNTHS',
    plain: 'The second envelope stage: after the attack peak, how long the value takes to fall to the sustain level.',
    why: 'Decay shapes the body of a note — snappy decay to low sustain reads as percussive; slow decay reads as singing.',
    studio: 'The knob that decides how fast the initial hit settles into the held tone.',
    uses: ['Amp envelopes', 'Filter plucks', 'Drum synthesis'],
    mistake: 'Confusing decay (fall *to sustain*, key held) with release (fade *after key-up*).',
    remember: 'Decay falls to sustain while the key is still down.',
    related: ['envelope', 'attack', 'sustain', 'release'],
    appears: [{ z: 4, label: 'envelope stages' }],
    search: ['fall', 'settle'],
  },
  {
    id: 'sustain', t: 'sustain', c: 'SYNTHS',
    plain: 'The third envelope stage — and the odd one out: it\'s a level, not a time. The value the envelope holds for as long as the key stays down.',
    why: 'Sustain 100% = organ; sustain 0% = pluck (the note dies even while held). Getting "level not time" right avoids a classic implementation bug.',
    studio: 'How loud the note stays while you hold the key.',
    uses: ['Amp envelopes', 'Filter hold levels', 'MIDI sustain pedal (related, different thing)'],
    mistake: 'Implementing sustain as a duration. It\'s a level held indefinitely — until note-off starts the release.',
    remember: 'Sustain is a level, not a time.',
    related: ['envelope', 'decay', 'release', 'midi'],
    appears: [{ z: 4, label: 'envelope stages' }, { z: 5, label: 'sustain pedal handling' }],
    search: ['hold', 'held level'],
  },
  {
    id: 'release', t: 'release', c: 'SYNTHS',
    plain: 'The final envelope stage: how long the value takes to fade to zero after the key is let go.',
    why: 'Release is why notes don\'t cut dead at note-off — and why a voice isn\'t free for stealing the instant its key lifts. Voices die when release *finishes*.',
    studio: 'The tail after your finger leaves the key.',
    uses: ['Note tails', 'Voice lifecycle', 'Reverb-like sustain'],
    mistake: 'Freeing a voice at note-off instead of at end-of-release — audible clicks as tails get cut.',
    remember: 'A note ends when release finishes, not when the finger lifts.',
    related: ['envelope', 'sustain', 'voice', 'voice-stealing'],
    appears: [{ z: 4, label: 'envelope stages' }, { z: 5, label: 'voice lifecycle' }],
    search: ['tail', 'fade out', 'let go'],
  },
  {
    id: 'filter', t: 'filter', c: 'EFFECTS',
    plain: 'A process that reduces some frequencies and keeps others: low-pass keeps lows, high-pass keeps highs, band-pass keeps a band. In code, a short feedback equation applied per sample.',
    why: 'The heart of subtractive synthesis and of every EQ. Your first filter (Zone 4) is a few lines that turn buzzy saws into warmth.',
    studio: 'The cutoff knob you\'ve automated a thousand times.',
    uses: ['Synth voices', 'EQs', 'DJ-style sweeps', 'De-essing'],
    viz: { t: 'filtercurve' },
    mistake: 'Modulating cutoff without smoothing, or pushing resonance until the feedback math blows up — filters need guard rails.',
    remember: 'A filter is a per-sample feedback equation shaping the spectrum.',
    related: ['cutoff', 'resonance', 'frequency', 'dsp'],
    appears: [{ z: 4, label: 'your first filter' }, { z: 7, label: 'filter effect mission' }],
    aka: ['lpf', 'hpf', 'low pass', 'high pass'],
    search: ['eq', 'brightness', 'muffle', 'sweep'],
  },
  {
    id: 'cutoff', t: 'cutoff', full: 'cutoff frequency', c: 'EFFECTS',
    plain: 'The frequency where a filter starts working — above it (low-pass) or below it (high-pass), frequencies are progressively reduced.',
    why: 'The single most automated knob in electronic music, and in code: one float, read by the filter equation, smoothed so sweeps don\'t zipper.',
    studio: 'THE knob. The one your hand finds without looking.',
    uses: ['Filter sweeps', 'Envelope→cutoff routing', 'LFO wobbles'],
    mistake: 'Setting cutoff in raw Hz on a linear knob — ears hear pitch logarithmically; map the knob exponentially.',
    remember: 'Cutoff is where the filter bites — map it logarithmically, smooth its moves.',
    related: ['filter', 'resonance', 'frequency', 'parameter-smoothing'],
    appears: [{ z: 4, label: 'filter parameters' }],
    search: ['brightness', 'sweep', 'frequency knob'],
  },
  {
    id: 'resonance', t: 'resonance', c: 'EFFECTS',
    plain: 'A boost right at the filter\'s cutoff frequency, created by feeding some filter output back into itself. High resonance rings; extreme resonance self-oscillates into a whistle.',
    why: 'Resonance is feedback, and feedback math can blow up — your filter code will clamp it. It\'s also what makes acid lines acid.',
    studio: 'The squelch knob — 303 territory.',
    uses: ['Acid basslines', 'Formant effects', 'Self-oscillating sines'],
    mistake: 'Letting users push resonance into numerical blowup — clamp the feedback range in your setter.',
    remember: 'Resonance is controlled feedback — musical until it isn\'t; clamp it.',
    related: ['filter', 'cutoff', 'gain'],
    appears: [{ z: 4, label: 'resonant filters' }],
    aka: ['q'],
    search: ['squelch', 'peak', 'acid', 'ring'],
  },
  {
    id: 'lfo', t: 'LFO', full: 'Low-Frequency Oscillator', c: 'SYNTHS',
    plain: 'An oscillator running below hearing range (say 0.1–20 Hz), used not as sound but as motion: its output wiggles other parameters — pitch for vibrato, amplitude for tremolo, cutoff for wobble.',
    why: 'Code-wise it\'s the same phase-advance oscillator you built, just slower — and its output patches into parameters instead of speakers. Modulation architecture starts here.',
    studio: 'The wobble source: vibrato, tremolo, auto-wah, dubstep bass — all LFO destinations.',
    uses: ['Vibrato (→pitch)', 'Tremolo (→amp)', 'Wobble (→cutoff)', 'Auto-pan'],
    viz: { t: 'wave', type: 'sine', caption: 'same oscillator — just slow, and aimed at a knob' },
    mistake: 'Updating LFO-modulated values once per block — fast LFOs need per-sample (or smoothed) application to avoid stair-stepping.',
    remember: 'An LFO is an oscillator aimed at a knob instead of a speaker.',
    related: ['oscillator', 'frequency', 'cutoff', 'automation'],
    appears: [{ z: 4, label: 'modulation' }, { z: 5, label: 'mod matrices' }, { z: 7, label: 'tremolo mission' }],
    search: ['wobble', 'vibrato', 'tremolo', 'modulation'],
  },
  {
    id: 'aliasing', t: 'aliasing', c: 'DSP',
    plain: 'What happens when you generate or create frequencies above half the sample rate: they fold back down as inharmonic, metallic wrong-pitched tones that were never supposed to exist.',
    why: 'Naive digital saws, hard distortion and fast modulation all alias. It\'s the signature "cheap digital" sound — and why pro plugins oversample or band-limit.',
    studio: 'That harsh inharmonic fizz on a cheap digital distortion — frequencies folding back where they don\'t belong.',
    uses: ['Why oscillators are band-limited', 'Why distortion oversamples', 'Sample-rate conversion'],
    mistake: 'Testing distortion only on low notes — aliasing screams on high notes where harmonics cross the fold-back line.',
    remember: 'Frequencies past half the sample rate don\'t disappear — they fold back wrong.',
    related: ['oversampling', 'sample-rate', 'waveform'],
    appears: [{ z: 4, label: 'aliasing & band-limiting' }],
    search: ['fold', 'harsh', 'digital sound', 'nyquist'],
  },
  {
    id: 'oversampling', t: 'oversampling', c: 'PERFORMANCE',
    plain: 'Temporarily running DSP at a multiple of the session\'s sample rate (2×, 4×…), processing, then converting back down. The extra headroom pushes aliasing out of the audible fold-back zone.',
    why: 'The standard cure for aliasing in distortions and saturators. Costs CPU and adds a little latency — a real engineering tradeoff you\'ll make.',
    studio: 'The 2x/4x quality switch on your favorite saturation plugin.',
    uses: ['Distortion & saturation', 'Clippers', 'Nonlinear filters'],
    mistake: 'Oversampling everything "for quality" — linear processes like gain and delay don\'t alias; you\'d burn CPU for nothing.',
    remember: 'Oversample nonlinear stages; linear ones don\'t need it.',
    related: ['aliasing', 'sample-rate', 'latency', 'cpu'],
    appears: [{ z: 4, label: 'oversampling' }],
    search: ['2x', '4x', 'quality mode', 'hq'],
  },
  {
    id: 'interpolation', t: 'interpolation', c: 'MATH',
    plain: 'Estimating the value *between* two known samples. Reading a delay line at 123.4 samples, or repitching a sample, needs values at fractional positions — interpolation invents them smoothly.',
    why: 'Fractional delays, pitch shifting, wavetable reading, sample playback at arbitrary rates — all live on interpolation. Linear (a straight line between neighbors) gets you far.',
    studio: 'Playing a sample back at a different pitch — the machine reads between the recorded points.',
    uses: ['Fractional delays', 'Sample repitching', 'Wavetable scanning', 'Chorus/flanger sweeps'],
    mistake: 'Rounding to whole sample positions instead — pitch wobbles and zipper noise on every modulated delay.',
    remember: 'Interpolation reads smoothly between samples — fractions matter.',
    related: ['sample', 'phase', 'lfo'],
    appears: [{ z: 4, label: 'delay lines & interpolation' }],
    search: ['between samples', 'fractional', 'smooth read'],
  },
  {
    id: 'voice', t: 'voice', c: 'SYNTHS',
    plain: 'One note-playing unit inside a synth: its own oscillators, envelope, and filter, playing one note at a time. A synth\'s polyphony is its voice count.',
    why: 'In code, a voice is one object of your Voice class — per-object state is what makes eight simultaneous notes possible. Managing them is Zone 5.',
    studio: 'The "voices: 8" spec on a classic polysynth — eight notes max, then something gives.',
    uses: ['Note playback', 'Polyphony', 'Unison stacking'],
    viz: { t: 'voices' },
    mistake: 'Sharing one envelope or phase across voices — every voice needs its own complete state.',
    remember: 'A voice is one self-contained note machine; polyphony is a team of them.',
    related: ['polyphony', 'voice-stealing', 'object', 'envelope', 'oscillator'],
    appears: [{ z: 5, label: 'voices & allocation' }],
    search: ['note', 'polysynth', 'simultaneous'],
  },
  {
    id: 'polyphony', t: 'polyphony', c: 'SYNTHS',
    plain: 'Playing multiple notes at once. A polyphonic synth keeps a pool of voices and assigns incoming notes to free ones; monophonic synths have exactly one voice.',
    why: 'Voice pools, note-to-voice assignment, and what to do when the pool runs dry (voice stealing) — the core engineering of Zone 5\'s synth work.',
    studio: 'Chords vs. bass lines: whether the instrument can say more than one thing at once.',
    uses: ['Chord playing', 'Voice pool sizing', 'CPU budgeting per voice'],
    mistake: 'Unbounded polyphony "so notes never cut" — each voice costs CPU; every real synth caps the pool.',
    remember: 'Polyphony is a fixed pool of voices and a plan for when it runs out.',
    related: ['voice', 'voice-stealing', 'cpu', 'midi'],
    appears: [{ z: 5, label: 'polyphony' }, { z: 7, label: 'poly synth mission' }],
    search: ['chords', 'multiple notes', 'mono poly'],
  },
  {
    id: 'voice-stealing', t: 'voice stealing', c: 'SYNTHS',
    plain: 'What a synth does when all voices are busy and a new note arrives: it steals one — usually the oldest or quietest — fades it fast, and reassigns it to the new note.',
    why: 'Without stealing, the 9th note on an 8-voice synth is silently dropped. With clumsy stealing, tails cut with clicks. Graceful stealing is an audible quality mark.',
    studio: 'Playing a 9-note chord on an 8-voice classic: one earlier note quietly bows out.',
    uses: ['Note priority rules', 'Fast-release fades', 'Sustain pedal interactions'],
    viz: { t: 'voices', steal: true },
    mistake: 'Hard-cutting the stolen voice — steal with a millisecond fade, or every busy passage clicks.',
    remember: 'When voices run out, steal gracefully — fade, then reassign.',
    related: ['voice', 'polyphony', 'release', 'midi'],
    appears: [{ z: 5, label: 'voice stealing' }],
    search: ['too many notes', 'cut off', 'note priority'],
  }
);
