/* ============================================================
   SIGNAL DICTIONARY — part I: terms introduced by Zone 7.
   Kept deliberately lean: only what the product line needs.
   ============================================================ */

DICT.push(
  {
    id: 'delay-line', t: 'delay line', c: 'EFFECTS',
    plain: 'A pre-allocated circular buffer with two moving positions: a write head recording the incoming audio, and a read head trailing it by the delay time in samples (seconds × rate). Both wrap at the end — a tape loop made of memory.',
    why: 'It\'s the engine inside delay, chorus, flanger and reverb — and a test of your bounds discipline: the read head\'s wrap math (C++ % keeps the dividend\'s sign!) is a classic crash site.',
    studio: 'A tape echo: one loop of tape passing a record head, then a playback head. The gap between heads is the delay time; the splice is the wrap.',
    uses: ['Delay & echo', 'Chorus/flanger (modulated, short)', 'Reverb networks'],
    viz: { t: 'delayviz' },
    mistake: 'Sizing the line from the CURRENT delay time instead of the maximum — the knob then triggers a mid-render reallocation (the forbidden verb). Buy max in prepareToPlay; the knob only moves the read head.',
    remember: 'Two heads on a circle: write now, read then. Size for the max, wrap by hand.',
    related: ['audio-buffer', 'feedback', 'wet-dry', 'interpolation'],
    appears: [{ z: 7, node: 'f1' }, { z: 7, node: 'p22' }, { z: 7, node: 'fb1' }],
    aka: ['circular buffer', 'tape loop', 'echo buffer'],
    search: ['echo', 'delay buffer', 'read head', 'write head'],
  },
  {
    id: 'feedback', t: 'feedback', c: 'EFFECTS',
    plain: 'Routing an effect\'s output back into its own input, scaled by a factor. In a delay: each echo re-records, quieter by the feedback amount — repeats that decay. At 1.0 or above, each pass reproduces or GROWS the last: the runaway.',
    why: 'Feedback is where echoes, resonance and screaming self-oscillation all come from — the same wire, different amounts. Clamping it below 1.0 is the difference between dub and disaster.',
    studio: 'The "regen" knob on every echo pedal — and, unclamped, the same physics as a mic pointed at its own monitor.',
    uses: ['Delay repeats', 'Filter resonance', 'Flanger intensity'],
    mistake: 'Clamping with the wrong ceiling (jlimit to 1.2 "for drama") — above 1.0 the loop gains energy every pass and the meltdown is exponential. Drama lives at 0.95; disaster starts at 1.0.',
    remember: 'Below 1.0: repeats decay. At 1.0: forever. Above: runaway. The clamp IS the product decision.',
    related: ['delay-line', 'resonance', 'gain', 'clipping'],
    appears: [{ z: 7, node: 'f1' }, { z: 7, node: 'p22' }, { z: 7, node: 'boss7' }],
    aka: ['regeneration', 'regen', 'repeats'],
    search: ['repeats', 'echo amount', 'runaway delay', 'self oscillation'],
  },
  {
    id: 'wet-dry', t: 'wet/dry mix', c: 'EFFECTS',
    plain: 'The blend between the processed signal (wet) and the untouched input (dry): out = dry × (1 − mix) + wet × mix. Mixing\'s plus sign (d11) wearing an effects costume — 0 is bypass-flavored, 1 is full effect, 0.5 is parallel processing.',
    why: 'Nearly every effect ships one, and it inherits the whole knob discipline automatically: atomic crossing, smoothing (a stepped mix zippers), state with defaults.',
    studio: 'Parallel compression\'s whole trick, generalized: the untouched take and the processed take on two faders, summed.',
    uses: ['Delay/reverb blend', 'Parallel saturation', 'Every effect\'s mix knob'],
    mistake: 'Computing mix with integer division (percent / 100) — the knob becomes a switch that does nothing until 100%. Zone 1\'s truncation trap loves this exact line.',
    remember: 'Two gains, one sum: dry fades out as wet fades in. Smooth it like any continuous knob.',
    related: ['mixing', 'gain', 'parameter-smoothing'],
    appears: [{ z: 7, node: 'fc1' }, { z: 7, node: 'p22' }, { z: 7, node: 'boss7' }],
    aka: ['mix knob', 'blend', 'parallel processing'],
    search: ['blend', 'mix', 'parallel', 'dry signal'],
  },
  {
    id: 'waveshaping', t: 'waveshaping', c: 'EFFECTS',
    plain: 'Distortion as a drawn rule: every sample passes through a fixed transfer curve, out = shape(in). A straight diagonal is a wire; a gentle bend (tanh) is warm saturation; snapped-flat ends are hard clipping\'s harsh corners.',
    why: 'The curve IS the pedal: reading transfer curves lets you understand every saturator, fuzz and tape emulation — and predict its harmonic recipe (bends = warm, corners = harsh, everything = new harmonics that must pay the Nyquist toll).',
    studio: 'Driving a console transformer or tape machine on purpose: push gently and it rounds the peaks — the "warmth" everyone chases is a curve\'s bend.',
    uses: ['Saturation & distortion', 'Drum-bus warmth (parallel)', 'Guitar amp sims'],
    viz: { t: 'shaperviz' },
    mistake: 'Shipping a shaper with no drive stage: tanh of clean ±1 audio barely bends. Drive pushes the signal INTO the curve\'s interesting region — it\'s the doorway, not decoration.',
    remember: 'The curve is the sound: drive in, compensation out, and every new harmonic risks folding (aliasing).',
    related: ['clipping', 'drive', 'harmonics', 'oversampling'],
    appears: [{ z: 7, node: 'f2' }, { z: 7, node: 'p24' }],
    aka: ['transfer curve', 'saturation', 'soft clipping', 'tanh'],
    search: ['distortion curve', 'saturation', 'warm drive', 'tanh'],
  },
  {
    id: 'drive', t: 'drive', c: 'EFFECTS',
    plain: 'Gain applied INTO a waveshaping curve: more drive pushes more of the signal into the bend, creating more harmonics. Honest designs pair it with output compensation so the knob changes TONE at constant loudness.',
    why: '"More, not just louder" is the whole point: uncompensated drive bribes the ear with level, and every A/B lies. Compensation is the oldest honesty tool in audio.',
    studio: 'The input gain on a preamp pushed hot on purpose, with the channel fader pulled down to match: the crunch changes, the loudness doesn\'t.',
    uses: ['Distortion amount', 'Saturation depth', 'Any shaped input stage'],
    mistake: 'Applying compensation BEFORE the shaper — it un-drives the distortion instead of trimming its loudness. Multiplication commutes; stages don\'t (d15\'s law).',
    remember: 'Drive pushes in, compensation trims out — tone changes, loudness holds.',
    related: ['waveshaping', 'gain', 'headroom'],
    appears: [{ z: 7, node: 'f2' }, { z: 7, node: 'p24' }],
    aka: ['input gain', 'saturation amount'],
    search: ['drive knob', 'more distortion', 'output compensation', 'makeup gain'],
  },
  {
    id: 'tempo-sync', t: 'tempo sync', c: 'DAWS',
    plain: 'Deriving time values from the host\'s tempo instead of milliseconds: 60 ÷ BPM = seconds per beat, scaled by a note-value ratio, then × sampleRate. Delays land on eighths, LFOs lock to bars — the effect joins the groove.',
    why: 'Musicians think in note values; hosts supply BPM (and automate it mid-song!) — synced effects must recompute live and GLIDE time changes, or every tempo nudge clicks.',
    studio: 'The tap-tempo button, automated: instead of tapping the delay into time, the session\'s clock IS the tap.',
    uses: ['Synced delays', 'Tempo-locked LFO wobbles', 'Gated/trance effects'],
    mistake: 'Treating sync as a load-time constant. Tempo is automatable — the conversion is live math, recomputed when BPM moves, with the resulting time glided (d13).',
    remember: '60/BPM, times the note ratio, times the rate — recomputed live, moved gently.',
    related: ['delay-line', 'lfo', 'daw', 'sample-rate'],
    appears: [{ z: 7, node: 'fc2' }, { z: 7, node: 'p22' }],
    aka: ['bpm sync', 'note values', 'tap tempo'],
    search: ['sync to tempo', 'eighth note delay', 'bpm', 'beat sync'],
  },
  {
    id: 'sample-playback', t: 'sample playback', c: 'SYNTHS',
    plain: 'An oscillator whose waveform is a recording: a playhead walks a stored buffer, advancing by a ratio each output sample. Ratio 1.0 plays as recorded; 2^(semitones/12) repitches — coupling pitch and speed (the chipmunk law).',
    why: 'It\'s the architecture behind samplers, drum machines and romplers — and a reuse exam: d5\'s bookmark, d3\'s pitch law, f1\'s interpolation and n5\'s per-voice split all reappear with a recording in the middle.',
    studio: 'A record player with a MIDI-controlled speed knob: higher keys spin faster — higher AND shorter, always together.',
    uses: ['Samplers & drum machines', 'Vocal chops', 'Looped sustains'],
    mistake: 'Reading truncated playhead positions without interpolation — gritty crunch at any ratio besides 1.0. Fractional positions blend their neighbors; it\'s three operations.',
    remember: 'A playhead over a recording: pitch is the step size, loops wrap, one-shots bound.',
    related: ['sample', 'interpolation', 'voice', 'envelope'],
    appears: [{ z: 7, node: 'f4' }, { z: 7, node: 'p28' }],
    aka: ['sampler', 'playhead', 'root note', 'repitching'],
    search: ['play samples', 'pitch a recording', 'chipmunk', 'looping'],
  }
);
