/* ============================================================
   SIGNAL DICTIONARY — part G: terms introduced by Zone 5.
   ============================================================ */

DICT.push(
  {
    id: 'note-event', t: 'note-on / note-off', c: 'MIDI',
    plain: 'The two messages that bracket every note: note-on says “this key went down, this hard” (channel + note number + velocity); note-off says “that key came up.” A note has no stored length — it lasts exactly until its off arrives.',
    why: 'Everything a synth does starts from these two events: allocation on the on, release on the off. And the classic bugs — stuck notes, wrong victims — are all failures to pair them correctly.',
    studio: 'The dots in your piano roll: each dot\'s left edge is a note-on, its right edge the note-off, its lane the note number. You\'ve been editing these messages for years.',
    uses: ['Starting voices', 'Releasing voices', 'Piano roll editing', 'Arpeggiators & sequencers'],
    viz: { t: 'keys', pressed: [7], msg: 'NOTE ON · note 60 · vel 100' },
    mistake: 'Forgetting the 1983 convention: a note-on with velocity 0 officially means note-OFF. Controllers still send it; JUCE\'s isNoteOff() honors it — raw-byte parsers get stuck notes.',
    remember: 'On starts a life, off starts its ending — and velocity 0 is an off in disguise.',
    related: ['midi', 'velocity', 'voice-allocation', 'release'],
    appears: [{ z: 5, node: 'n1' }, { z: 5, node: 'n3' }, { z: 5, node: 'p12' }],
    aka: ['note on', 'note off', 'key event'],
    search: ['key press', 'key release', 'note message', 'stuck note'],
  },
  {
    id: 'aftertouch', t: 'aftertouch', c: 'MIDI',
    plain: 'Pressure applied to a key AFTER it bottoms out — lean into a held note and the synth responds. Channel pressure sends one value for the whole keyboard; polyphonic aftertouch (rare, glorious) sends pressure per key.',
    why: 'It\'s expression for the note you\'re already holding — swells, brightness, vibrato — without touching a wheel. Route it like any control signal: another source in the matrix.',
    studio: 'A violinist adding bow pressure mid-note. The strike happened; the LEANING is a second, continuous gesture on top.',
    uses: ['Swells on held notes', 'Vibrato without the wheel', 'Per-finger expression (poly AT / MPE)'],
    mistake: 'Confusing aftertouch with velocity. Velocity is the strike — captured once, at the start. Aftertouch is pressure DURING the note — continuous, and a separate message type entirely.',
    remember: 'Velocity is how you hit; aftertouch is how you lean.',
    related: ['velocity', 'cc', 'mod-matrix', 'mod-wheel'],
    appears: [{ z: 5, node: 'n12' }],
    aka: ['channel pressure', 'poly aftertouch', 'key pressure'],
    search: ['pressure', 'lean into key', 'expression', 'mpe'],
  },
  {
    id: 'sustain-pedal', t: 'sustain pedal (CC 64)', c: 'MIDI',
    plain: 'The hold pedal, spoken as Continuous Controller 64: value ≥64 means down, <64 means up. While down, the synth defers note-offs — released keys keep ringing; pedal-up fires all the deferred releases at once.',
    why: 'It\'s pure bookkeeping with famous failure modes: stuck notes come from lost pedal-up handling or stale “sustained” marks on reused voices. Every synth and piano plugin implements this deferral.',
    studio: 'A bartender holding tabs open: every “I\'m leaving” goes on the tab instead of being settled. Foot up = last call — all tabs settle in one instant.',
    uses: ['Piano-style playing', 'Pad washes', 'Every keyboard patch you ship'],
    viz: { t: 'pedalviz' },
    mistake: 'Implementing pedal-down (notes hang — demos great!) and forgetting pedal-up\'s release loop. The wash grows forever. Both halves or neither.',
    remember: 'The pedal defers goodbyes: down = mark instead of release, up = fire every mark.',
    related: ['cc', 'release', 'note-event', 'panic'],
    appears: [{ z: 5, node: 'n10' }, { z: 5, node: 'nc3' }],
    aka: ['hold pedal', 'damper pedal', 'cc64'],
    search: ['pedal', 'hold notes', 'notes hang', 'damper'],
  },
  {
    id: 'monophonic', t: 'monophonic vs polyphonic', c: 'SYNTHS',
    plain: 'Monophonic: one note at a time — new keys replace the current pitch by a priority rule (last-note is the modern default). Polyphonic: multiple simultaneous notes, one voice each. Neither is “better”: mono is a personality, poly is a capacity.',
    why: 'Mono needs held-note tracking (release a key, fall back to the one still held); poly needs allocation, ownership and stealing. The two designs share voices but not government.',
    studio: 'A solo horn player versus a choir. The horn player has technique for overlapping requests (slides, restatements); the choir just assigns another singer.',
    uses: ['Mono basses & leads', 'Poly pads & keys', 'Legato/portamento modes'],
    mistake: 'Building mono as “poly with one voice” and skipping the held-notes list — then every overlapped release chops the phrase instead of falling back to the held key.',
    remember: 'Mono = one voice + rules; poly = many voices + management.',
    related: ['voice', 'polyphony', 'legato', 'retrigger'],
    appears: [{ z: 5, node: 'n4' }],
    aka: ['mono', 'poly', 'note priority'],
    search: ['one note at a time', 'mono mode', 'note priority', 'fall back'],
  },
  {
    id: 'legato', t: 'legato', c: 'SYNTHS',
    plain: 'A mono mode where overlapped notes share one envelope ride: press a new key while holding another and the pitch changes but no new attack fires — notes bind into one phrase. Add a pitch glide and it becomes portamento.',
    why: 'It\'s the difference between a mono line that flows and one that stutters. One if-statement (retrigger only when the synth was silent) implements the entire feel.',
    studio: 'A singer moving between words without taking a breath. Same voice, new pitch, unbroken phrase — the breath (attack) only happens when a phrase starts.',
    uses: ['Mono leads & basses', '303-style lines', 'Portamento (legato + glide)'],
    mistake: 'Calling noteOn() unconditionally on every note — legato becomes impossible, and every overlapped note stabs a fresh attack: typewriter fire where a phrase should be.',
    remember: 'Legato = new pitch, same breath. The retrigger if IS the mono feel switch.',
    related: ['retrigger', 'monophonic', 'envelope'],
    appears: [{ z: 5, node: 'n4' }],
    aka: ['legato mode', 'portamento', 'glide'],
    search: ['smooth notes', 'no retrigger', 'slide between notes', 'glide'],
  },
  {
    id: 'retrigger', t: 'retrigger', c: 'SYNTHS',
    plain: 'Restarting the envelope from its attack when a new note arrives — every note gets a fresh strike. The opposite of legato. In poly synths, also what happens when a stolen or repeated voice starts its new note.',
    why: 'Punchy and rhythmic where legato is smooth — and in voice stealing, the restart is where clicks are born: a fresh attack slammed onto a mid-level waveform needs a quick fade first.',
    studio: 'A guitarist picking every note versus hammering-on. Picking = retrigger: each note gets its own transient attack.',
    uses: ['Rhythmic mono lines', 'Voice stealing restarts', 'Vibrato LFOs that reset per note'],
    mistake: 'Restarting a stolen voice instantly at full attack from wherever its waveform sat — a vertical step, a click, on every steal. Fade the victim a few ms first.',
    remember: 'Retrigger = fresh attack per note. Punch for phrases, care for steals.',
    related: ['legato', 'envelope', 'voice-stealing', 'attack'],
    appears: [{ z: 5, node: 'n4' }, { z: 5, node: 'boss5' }],
    aka: ['re-trigger', 'envelope restart'],
    search: ['fresh attack', 'restart envelope', 'punchy notes'],
  },
  {
    id: 'voice-allocation', t: 'voice allocation', c: 'SYNTHS',
    plain: 'The bookkeeping that seats notes at voices: note-on hunts the pool for a free card (note == −1), stamps ownership, and starts it; note-off hunts by that stamp to release exactly the right voice.',
    why: 'The two classic synth bugs live here: the stuck note (an off that finds no owner) and the wrong victim (an off that ignores stamps). Allocation is small code with enormous audible consequences.',
    studio: 'A stage manager with a clipboard: gig in → first free player takes the chart, name goes on the board. Song ends → the manager checks the BOARD, not the seating order, to know who stops.',
    uses: ['Every note-on/off pair', 'Voice stealing (its overflow path)', 'Duplicate-note policies'],
    viz: { t: 'voicecards', cards: [{ note: 'C4', state: 'busy' }, { note: 'E4', state: 'busy' }, { note: '—', state: 'alloc' }, { note: '—', state: 'free' }] },
    mistake: 'Testing by releasing keys in reverse press order — which accidentally works even with broken ownership. Release the MIDDLE note of a chord: that\'s the test that catches clipboard-free code.',
    remember: 'Every note-off is a search. The note field is the clipboard; −1 means for hire.',
    related: ['voice', 'voice-stealing', 'polyphony', 'note-event'],
    appears: [{ z: 5, node: 'n7' }, { z: 5, node: 'nr3' }, { z: 5, node: 'p13' }],
    aka: ['note assignment', 'voice management'],
    search: ['assign notes', 'which voice', 'free voice', 'ownership'],
  },
  {
    id: 'panic', t: 'panic (all notes off)', c: 'MIDI',
    plain: 'The emergency brake: release every voice, clear every pedal mark, reset all performance state. MIDI dedicates CC 123 (All Notes Off) to it; hosts send it on stop, and synth UIs add a panic button that calls the same code.',
    why: 'Note-offs get lost — cables drop, loops truncate, sequencers crash — and the result is a note that never ends. Panic is the guaranteed way out, and it must reset ALL state or it just schedules the next emergency.',
    studio: 'The house lights: one switch that ends every scene at once, no exceptions, no waiting for anyone\'s foot or fingers.',
    uses: ['Host stop handling (CC 123)', 'UI panic buttons', 'Recovering from stuck notes'],
    mistake: 'Releasing envelopes but leaving sustained marks and pedalDown untouched — the voices go quiet, the stale state sticks the NEXT notes. Panic means everything.',
    remember: 'Panic is a state reset wearing a mute button — marks, pedal, envelopes, all of it.',
    related: ['sustain-pedal', 'note-event', 'cc'],
    appears: [{ z: 5, node: 'n15' }, { z: 5, node: 'p15' }],
    aka: ['all notes off', 'cc123', 'midi panic'],
    search: ['stuck notes', 'kill all notes', 'emergency stop', 'reset synth'],
  },
  {
    id: 'mod-matrix', t: 'modulation matrix', c: 'SYNTHS',
    plain: 'Routing as data: a table where each row says source → destination × amount (LFO → pitch × 0.3). One loop applies every row; multiple rows aimed at one destination ADD, like a control-signal mix bus.',
    why: 'It replaces a pile of hand-wired ifs with rows you can add, remove and automate — and it\'s how every serious synth\'s mod page works. Reading rows as sentences is reading any synth.',
    studio: 'A patchbay for invisible hands: every row is one cable — from a mover, to a knob, with an attenuator in line. The synth walks the bay top to bottom, every sample.',
    uses: ['LFO→pitch (vibrato)', 'Velocity→gain', 'Wheel→depth', 'Key track→brightness'],
    viz: { t: 'modmatrix', rows: [['LFO 1', 'PITCH', 0.3], ['WHEEL', 'LFO DEPTH', 1.0], ['VELOCITY', 'GAIN', 0.8]] },
    mistake: 'Forgetting negative amounts — half of sound design is routing things DOWN (wheel closes the filter, tracking darkens high notes). A matrix without minus signs is half a matrix.',
    remember: 'Source, destination, amount. Rows are sentences; sums make them music.',
    related: ['modulation', 'lfo', 'keyboard-tracking', 'mod-wheel'],
    appears: [{ z: 5, node: 'n13' }],
    aka: ['mod matrix', 'routing matrix', 'mod page'],
    search: ['routing', 'source destination', 'modulation page', 'assign lfo'],
  },
  {
    id: 'keyboard-tracking', t: 'keyboard tracking', c: 'SYNTHS',
    plain: 'Using the note number itself as a modulation source: higher keys push a destination up, lower keys pull it down, normalized around an anchor (usually middle C). Classic destination: filter brightness.',
    why: 'Real instruments change character across their range — one fixed cutoff flatters C2 and strangles C6. Tracking makes a single patch playable across the whole keyboard.',
    studio: 'A lighting rig that follows the singer across the stage: nobody moves a spotlight per note — POSITION drives the light.',
    uses: ['Filter cutoff across the range', 'Envelope times (shorter up high, like a piano)', 'Level compensation'],
    viz: { t: 'keytrack' },
    mistake: 'Tracking only upward. Amounts can be negative — darkening high notes is as musical as brightening them, and middle-C-anchored tracking pushes BOTH directions.',
    remember: 'The keyboard is a mod source: position in, parameter out, anchored at middle C.',
    related: ['mod-matrix', 'cutoff', 'frequency'],
    appears: [{ z: 5, node: 'n13' }],
    aka: ['key tracking', 'key follow', 'kbd track'],
    search: ['brighter high notes', 'filter follows keyboard', 'key follow'],
  },
  {
    id: 'unison', t: 'unison', c: 'SYNTHS',
    plain: 'One key, several voice copies: each detuned a few cents from its neighbors and panned across the stereo field. Their slow interference is the shimmer in every supersaw lead and anthem pad.',
    why: 'It\'s the biggest “expensive sound” trick in synthesis — and it has a bill: N-voice unison multiplies voice demand by N, so an 8-voice pool plays less than two 5-copy notes before stealing begins.',
    studio: 'A string section: twelve players on one line, each humanly imperfect, seated across the stage. One perfect violin is a soloist; twelve imperfect ones are a SECTION.',
    uses: ['Supersaw leads', 'Anthem pads', 'Thickening any patch'],
    viz: { t: 'unisonviz' },
    mistake: 'Detuning every copy off-center with none at 0 cents — the note loses its pitch anchor and reads as out of tune rather than wide. Keep one copy honest.',
    remember: 'Detune in cents, spread across the stage, keep one copy at zero — and pay the polyphony bill.',
    related: ['detune', 'polyphony', 'voice-stealing', 'stereo'],
    appears: [{ z: 5, node: 'n14' }, { z: 5, node: 'p15' }],
    aka: ['unison mode', 'supersaw', 'voice stacking'],
    search: ['thick lead', 'wide sound', 'supersaw', 'stack voices'],
  },
  {
    id: 'detune', t: 'detune (cents)', c: 'SYNTHS',
    plain: 'Deliberate small pitch offsets, measured in cents — hundredths of a semitone. Ratio = 2^(cents/1200). A few cents between stacked copies creates slow, animated beating: the chorus/unison shimmer.',
    why: 'Cents are the working currency of thickness: ±5 is subtle warmth, ±15 is a supersaw, ±50 is out-of-tune. And the /1200 in the formula is a classic bug site (÷12 turns shimmer into an octave catastrophe).',
    studio: 'A 12-string guitar: paired strings tuned almost-but-not-quite together. The almost is the instrument\'s entire personality.',
    uses: ['Unison stacks', 'Chorus effects', 'Oscillator “fatness” knobs'],
    mistake: 'Reading cents as semitones in code — dividing by 12 instead of 1200. Your ±12-cent shimmer becomes ±a whole octave, and the patch becomes performance art.',
    remember: '100 cents to the semitone, 1200 to the octave: 2^(cents/1200).',
    related: ['unison', 'frequency', 'phase'],
    appears: [{ z: 5, node: 'n14' }, { z: 5, node: 'p15' }],
    aka: ['cents', 'fine tune', 'detuning'],
    search: ['cents', 'fine tuning', 'slightly out of tune', 'fat sound'],
  }
);
