/* ============================================================
   SIGNAL DICTIONARY — part C: JUCE, Plugin Dev, MIDI, Tools,
   Debugging, DAWs, Architecture. Appended to DICT.
   ============================================================ */

DICT.push(

  /* ================= JUCE ================= */
  {
    id: 'juce', t: 'JUCE', full: 'Jules\' Utility Class Extensions', c: 'JUCE',
    plain: 'The dominant C++ framework for building audio plugins: one codebase that builds VST3, AU, AAX and standalone apps, with audio, MIDI, UI and parameter systems included.',
    why: 'It\'s the most widely used plugin framework — a huge share of commercial plugins are built on it. Zones 3+ of this course live in it.',
    studio: 'The mixing desk of plugin development: everything patched and ready, so you build the music, not the wiring.',
    uses: ['Plugin formats', 'AudioBuffer & MIDI', 'UI components', 'Parameters (APVTS)'],
    mistake: 'Learning JUCE before C++ basics — JUCE is C++ all the way down, which is why this course does C++ first.',
    remember: 'JUCE turns one C++ codebase into every plugin format.',
    related: ['audioprocessor', 'apvts', 'vst3', 'cmake'],
    appears: [{ z: 3, label: 'the whole zone' }],
    search: ['framework', 'library', 'plugin sdk'],
  },
  {
    id: 'audioprocessor', t: 'AudioProcessor', c: 'JUCE',
    plain: 'The JUCE class your plugin *is*. You inherit it and fill in its methods — prepareToPlay, processBlock, state save/load — and the host talks to your plugin entirely through them.',
    why: 'This is the frame every plugin hangs on. Understand its lifecycle and you understand how DAWs and plugins communicate.',
    studio: 'The chassis of the rack unit: power, jacks and mounting standardized, your circuit inside.',
    uses: ['Every plugin\'s core class', 'DSP lifecycle', 'State saving'],
    viz: { t: 'chain', nodes: ['HOST', 'AudioProcessor', 'audio out'], accent: 1, caption: 'the host talks only through its methods' },
    mistake: 'Doing UI work inside it — the processor is the engine; the editor (a separate class) is the panel.',
    remember: 'Your plugin IS an AudioProcessor — the host speaks only through its methods.',
    related: ['processblock', 'preparetoplay', 'audioprocessoreditor', 'class'],
    appears: [{ z: 3, label: 'AudioProcessor lifecycle' }],
    search: ['plugin class', 'processor'],
  },
  {
    id: 'audioprocessoreditor', t: 'AudioProcessorEditor', c: 'JUCE',
    plain: 'The JUCE class for your plugin\'s window: knobs, meters, graphics. It runs on the UI thread, may not exist at all (headless hosts), and gets created/destroyed as users open and close the window.',
    why: 'The editor\'s come-and-go lifetime is why audio code must never assume it exists — a top source of real crashes.',
    studio: 'The faceplate: what people touch. The engine keeps running whether or not the faceplate is visible.',
    uses: ['Knobs & sliders', 'Meters & scopes', 'Preset browsers'],
    mistake: 'Storing audio state in the editor — it dies when the window closes. State lives in the processor; the editor only displays it.',
    remember: 'The editor is a temporary window onto a permanent engine.',
    related: ['audioprocessor', 'ui-thread', 'apvts', 'gui'],
    appears: [{ z: 3, label: 'editors & attachments' }],
    aka: ['editor'],
    search: ['window', 'interface', 'knobs on screen'],
  },
  {
    id: 'preparetoplay', t: 'prepareToPlay()', c: 'JUCE',
    plain: 'The method the host calls before audio starts, handing you the sample rate and maximum block size. Your backstage moment: size buffers, reset state, precompute tables.',
    why: 'It\'s the one sanctioned place to allocate. Everything the audio thread will need must be ready when this returns.',
    studio: 'Soundcheck: patch everything, set levels, tune — before the doors open.',
    uses: ['Sizing delay lines', 'Resetting envelopes/phases', 'Computing wavetables'],
    mistake: 'Assuming it runs once — hosts call it again on sample-rate or buffer changes. Make it safely re-runnable.',
    remember: 'prepareToPlay is soundcheck: allocate and reset everything here.',
    related: ['processblock', 'releaseresources', 'sample-rate', 'allocation'],
    appears: [{ z: 1, node: 'c3' }, { z: 3, label: 'the lifecycle' }],
    search: ['setup', 'before playback', 'soundcheck'],
  },
  {
    id: 'processblock', t: 'processBlock()', c: 'JUCE',
    plain: 'The audio callback itself: the host hands you an audio buffer and a MIDI buffer; you process them in place before the deadline. Called hundreds of times per second on the audio thread.',
    why: 'Every piece of DSP you ever ship runs inside this method. Its real-time rules (no allocation, no locks, no I/O) define audio programming.',
    studio: 'The performance: the tape op hands you the reel, you process it live, no retakes.',
    uses: ['All your DSP', 'MIDI event handling', 'Metering taps'],
    viz: { t: 'chain', nodes: ['audio + MIDI in', 'processBlock()', 'processed out'], accent: 1 },
    mistake: 'Anything with unpredictable timing inside it: allocation, file access, locks, logging, UI calls.',
    remember: 'processBlock is the performance — bounded work only, every time.',
    related: ['audio-callback', 'audio-thread', 'audio-buffer', 'preparetoplay'],
    appears: [{ z: 1, node: 'c6' }, { z: 1, node: 'b4' }, { z: 3, label: 'processBlock deep dive' }],
    search: ['callback', 'process', 'main audio function'],
  },
  {
    id: 'releaseresources', t: 'releaseResources()', c: 'JUCE',
    plain: 'The method the host calls when audio stops — playback ends or the plugin is deactivated. Your chance to free big temporary resources the audio path was using.',
    why: 'Completes the lifecycle triangle: prepareToPlay (setup) → processBlock (play) → releaseResources (teardown). Well-behaved plugins clean up here.',
    studio: 'Load-out: strike the gear when the show closes.',
    uses: ['Freeing scratch memory', 'Stopping background work'],
    mistake: 'Forgetting that prepareToPlay may follow again — release/prepare can cycle many times per session.',
    remember: 'Setup, play, teardown — releaseResources closes the loop.',
    related: ['preparetoplay', 'processblock', 'destructor'],
    appears: [{ z: 3, label: 'the lifecycle' }],
    search: ['cleanup', 'stop', 'teardown'],
  },
  {
    id: 'apvts', t: 'APVTS', full: 'AudioProcessorValueTreeState', c: 'JUCE',
    plain: 'JUCE\'s parameter system: you declare every knob (name, range, default) in one layout; it syncs values with the host, makes every knob automatable, attaches UI controls, and saves/loads state.',
    why: 'The bridge between the audio thread, the UI thread and the host. Nearly every modern JUCE plugin is built around one.',
    studio: 'The patch memory + automation brain: every knob declared, recallable, and automatable.',
    uses: ['Parameter layouts', 'Slider attachments', 'Preset save/load', 'Host automation'],
    mistake: 'Bypassing it with raw member variables for knobs — you lose automation, state saving and thread safety in one stroke.',
    remember: 'Declare every knob in APVTS — automation and presets come free.',
    related: ['parameter', 'automation', 'preset', 'audioprocessor', 'ui-thread'],
    appears: [{ z: 3, label: 'APVTS & attachments' }],
    aka: ['value tree', 'AudioProcessorValueTreeState'],
    search: ['parameters', 'knob system', 'state', 'save settings'],
  },

  /* ================= PLUGIN DEV ================= */
  {
    id: 'plugin', t: 'plugin', c: 'PLUGIN DEV',
    plain: 'A piece of software that loads inside a host (your DAW) to process or generate audio. It doesn\'t run on its own — the host feeds it audio, MIDI, and a place to draw its window.',
    why: 'Understanding the guest-in-a-host relationship explains everything: why callbacks exist, why crashes kill the DAW, why formats matter.',
    studio: 'Outboard gear for the software age — racked inside the DAW instead of beside it.',
    uses: ['Effects', 'Instruments', 'Meters & analyzers'],
    viz: { t: 'chain', nodes: ['DAW (host)', 'your plugin', 'mix bus'], accent: 1 },
    mistake: 'Forgetting you\'re a guest: a plugin that hogs CPU or crashes takes the whole session down with it.',
    remember: 'A plugin is a guest in the host\'s house — a polite one survives.',
    related: ['host', 'daw', 'vst3', 'audioprocessor'],
    appears: [{ z: 3, label: 'plugin anatomy' }],
    search: ['vst', 'effect', 'instrument'],
  },
  {
    id: 'host', t: 'host', c: 'PLUGIN DEV',
    plain: 'The application that loads plugins — usually a DAW, sometimes a live rig or plugin validator. It owns the audio driver, the transport, and calls every plugin\'s callback in turn.',
    why: 'Hosts differ in how they call you: block sizes, automation timing, state handling. "Works in one host" is the start of testing, not the end.',
    studio: 'The venue: it books you, sets the schedule, and controls the PA.',
    uses: ['Callback scheduling', 'Automation playback', 'Plugin validation'],
    mistake: 'Testing in a single DAW. Each host exercises your plugin differently — pros validate across several.',
    remember: 'The host runs the show; plugins play the slots they\'re given.',
    related: ['plugin', 'daw', 'automation'],
    appears: [{ z: 6, label: 'DAW validation' }],
    search: ['daw', 'loads plugins'],
  },
  {
    id: 'daw', t: 'DAW', full: 'Digital Audio Workstation', c: 'DAWS',
    plain: 'The software where music gets made — Ableton Live, FL Studio, Logic, Cubase, Pro Tools, Reaper. As a plugin developer, the DAW is the host that runs your code.',
    why: 'You\'ve used DAWs for years as an instrument; now you\'ll meet them as runtime environments with different quirks, formats, and validation rules.',
    studio: 'The studio itself — desk, tape machine and patchbay in one window.',
    uses: ['Hosting your plugins', 'Automation & transport', 'Testing across vendors'],
    mistake: 'Assuming all DAWs behave alike — buffer patterns, automation resolution and plugin scanning all differ.',
    remember: 'To a plugin developer, a DAW is a runtime environment with opinions.',
    related: ['host', 'plugin', 'automation'],
    appears: [{ z: 6, label: 'DAW validation' }],
    aka: ['ableton', 'fl studio', 'logic', 'reaper', 'cubase', 'pro tools'],
    search: ['ableton', 'fl', 'logic', 'music software'],
  },
  {
    id: 'preset', t: 'preset', c: 'PLUGIN DEV',
    plain: 'A saved snapshot of every parameter — the plugin\'s complete recallable state. Load it and every knob returns to where it was.',
    why: 'State save/restore is a hard product requirement: sessions must reopen exactly as saved, and old presets must still load in new versions (version migration, Zone 6).',
    studio: 'Patch memory — the reason you can find that bass sound from last March.',
    uses: ['Factory banks', 'Session state', 'A/B comparisons'],
    mistake: 'Renaming or renumbering parameters between versions without a migration path — old sessions load scrambled.',
    remember: 'A preset is the promise that state can always come back.',
    related: ['apvts', 'automation', 'parameter'],
    appears: [{ z: 3, label: 'ValueTree state' }, { z: 5, node: 'n12' }, { z: 6, label: 'version migration' }],
    aka: ['patch'],
    search: ['save', 'recall', 'snapshot', 'patch'],
  },
  {
    id: 'automation', t: 'automation', c: 'PLUGIN DEV',
    plain: 'The DAW recording and replaying knob movements over time. During playback, the host streams parameter changes into your plugin — sometimes hundreds per second.',
    why: 'Your parameters must handle rapid outside changes smoothly (no zipper noise) and thread-safely — automation is the stress test of parameter design.',
    studio: 'Drawn fader rides and filter sweeps in your arrangement — now arriving as data into your own code.',
    uses: ['Fader rides', 'Filter sweeps', 'Testing parameter smoothing'],
    mistake: 'Reading parameters without smoothing — automation turns every step into a click.',
    remember: 'Automation is the host playing your knobs — be ready for fast hands.',
    related: ['apvts', 'parameter-smoothing', 'parameter', 'host'],
    appears: [{ z: 3, label: 'parameters & hosts' }, { z: 6, label: 'automation testing' }],
    search: ['fader rides', 'recorded knobs', 'moving parameters'],
  },
  {
    id: 'vst', t: 'VST', full: 'Virtual Studio Technology', c: 'PLUGIN DEV',
    plain: 'Steinberg\'s plugin standard — the family name behind "VST plugin." The current version is VST3; the older VST2 is discontinued for new development.',
    why: 'It\'s the format this whole course ships toward. JUCE generates VST3 from your AudioProcessor without format-specific code.',
    studio: 'The universal rack-mount standard of software gear.',
    uses: ['Windows standard', 'Cross-DAW distribution'],
    mistake: 'Chasing VST2 — licenses are no longer granted. New plugins target VST3 (plus AU on Mac).',
    remember: 'VST is the family; VST3 is the format you\'ll actually build.',
    related: ['vst3', 'au', 'aax', 'plugin'],
    appears: [{ z: 3, label: 'formats & builds' }],
    search: ['plugin format', 'steinberg'],
  },
  {
    id: 'vst3', t: 'VST3', full: 'Virtual Studio Technology 3', c: 'PLUGIN DEV',
    plain: 'The current VST standard: a .vst3 bundle supported by nearly every DAW on Windows and most elsewhere. Adds proper parameter handling, sidechains and per-note expression over VST2.',
    why: 'The primary build target of this course — "make a VST3" is literally the goal on the box.',
    studio: 'The current-generation connector standard — what new gear ships with.',
    uses: ['Your build target', 'Windows & cross-platform DAWs'],
    mistake: 'Editing/moving the built .vst3 by hand while a DAW has it loaded — build systems and scanners get confused; rebuild and rescan instead.',
    remember: 'VST3 is the format your CMake build produces at the end of this road.',
    related: ['vst', 'au', 'cmake', 'juce'],
    appears: [{ z: 3, label: 'VST3 builds' }, { z: 7, label: 'shipping missions' }],
    search: ['.vst3', 'format', 'build target'],
  },
  {
    id: 'au', t: 'AU', full: 'Audio Units', c: 'PLUGIN DEV',
    plain: 'Apple\'s plugin format — what Logic Pro and GarageBand load. Mac-only, validated by Apple\'s auval tool before a host will trust it.',
    why: 'Shipping on Mac means shipping AU alongside VST3. JUCE builds both from the same code; auval failures are a rite of passage.',
    studio: 'The Mac studio\'s house connector standard.',
    uses: ['Logic & GarageBand support', 'Mac distribution'],
    mistake: 'Skipping auval until release week — validate early; its errors are specific and fixable.',
    remember: 'AU is the Logic-and-Mac format — auval is its gatekeeper.',
    related: ['auv3', 'vst3', 'aax', 'juce'],
    appears: [{ z: 6, label: 'DAW validation' }],
    aka: ['audio unit', 'auval'],
    search: ['logic', 'mac format', 'apple'],
  },
  {
    id: 'auv3', t: 'AUv3', full: 'Audio Units version 3', c: 'PLUGIN DEV',
    plain: 'The modern, sandboxed generation of Audio Units — and the plugin format of iPhone and iPad music apps. Distributed through the App Store.',
    why: 'If your plugin should run in mobile DAWs (AUM, Logic for iPad, GarageBand iOS), AUv3 is the door. JUCE can target it.',
    studio: 'Rack gear for the iPad rig.',
    uses: ['iOS/iPadOS plugins', 'Sandboxed Mac hosts'],
    mistake: 'Assuming desktop UI translates directly — touch screens and small windows need real design attention.',
    remember: 'AUv3 is how plugins reach iPhone and iPad.',
    related: ['au', 'vst3', 'plugin'],
    appears: [{ z: 7, label: 'beyond desktop (future)' }],
    search: ['ios', 'ipad', 'mobile plugin'],
  },
  {
    id: 'aax', t: 'AAX', full: 'Avid Audio eXtension', c: 'PLUGIN DEV',
    plain: 'Avid\'s plugin format — the only one Pro Tools loads. Building it requires Avid\'s SDK and, for release, plugin signing through their program.',
    why: 'Pro Tools studios are a real market. JUCE supports AAX, but the signing/distribution hoops make it a later-stage step, not a first target.',
    studio: 'The house standard of the big tracking rooms.',
    uses: ['Pro Tools support', 'Commercial distribution'],
    mistake: 'Worrying about AAX on day one — ship VST3/AU first; add AAX when Pro Tools users ask.',
    remember: 'AAX = Pro Tools; save it for when you\'re shipping seriously.',
    related: ['vst3', 'au', 'plugin'],
    appears: [{ z: 7, label: 'commercial release (future)' }],
    search: ['pro tools', 'avid'],
  },

  /* ================= MIDI ================= */
  {
    id: 'midi', t: 'MIDI', full: 'Musical Instrument Digital Interface', c: 'MIDI',
    plain: 'The universal language of musical events: not sound, but messages — "note 60 pressed at velocity 100," "mod wheel moved," "sustain pedal down." Tiny, timestamped, and 40+ years universal.',
    why: 'Your synth receives MIDI in processBlock (a MidiBuffer alongside the audio) and turns messages into voices. Parsing note-on/note-off correctly is the gateway to instruments.',
    studio: 'The piano-roll data in your DAW — every dot is a message, not a sound.',
    uses: ['Synth input', 'Controller mapping', 'Arpeggiators', 'Drum triggers'],
    viz: { t: 'midimsg' },
    mistake: 'Treating MIDI as audio — it\'s events with timestamps. A note-on at sample 240 must start the voice mid-block, not at the block edge.',
    remember: 'MIDI is messages about music, never the sound itself.',
    related: ['velocity', 'cc', 'pitch-bend', 'processblock', 'voice'],
    appears: [{ z: 3, label: 'MIDI buffers' }, { z: 5, node: 'n1' }],
    search: ['notes', 'keyboard', 'piano roll', 'messages'],
  },
  {
    id: 'velocity', t: 'velocity', c: 'MIDI',
    plain: 'How hard a note was struck: 1–127, carried inside every note-on message. (Velocity 0 traditionally means note-off.)',
    why: 'Velocity → loudness is the minimum; velocity → filter brightness and envelope speed is what makes a synth feel alive under fingers.',
    studio: 'The difference between brushing a key and hammering it.',
    uses: ['Loudness scaling', 'Brightness (→cutoff)', 'Sample layer switching'],
    mistake: 'Mapping velocity to gain linearly — perception is curved; most instruments apply a velocity curve.',
    remember: 'Velocity is strike strength: 1–127, curved before it hits the gain.',
    related: ['midi', 'gain', 'envelope', 'voice'],
    appears: [{ z: 5, node: 'n2' }],
    search: ['hit strength', 'how hard', 'dynamics'],
  },
  {
    id: 'pitch-bend', t: 'pitch bend', c: 'MIDI',
    plain: 'The wheel that bends pitch smoothly — sent as its own high-resolution MIDI message (16,384 steps, center = no bend), separate from notes.',
    why: 'Your synth applies bend by scaling every active voice\'s frequency — a per-voice multiplication and a range setting (usually ±2 semitones).',
    studio: 'The left-hand wheel — whammy for keyboards.',
    uses: ['Lead expression', 'Slides', 'MPE-style per-note bend (later)'],
    mistake: 'Applying bend only to new notes — it must retune already-sounding voices live.',
    remember: 'Pitch bend retunes sounding voices in real time — center means no bend.',
    related: ['midi', 'frequency', 'mod-wheel', 'voice'],
    appears: [{ z: 5, node: 'n11' }, { z: 5, node: 'nc4' }],
    search: ['bend wheel', 'slide', 'whammy'],
  },
  {
    id: 'mod-wheel', t: 'mod wheel', full: 'modulation wheel', c: 'MIDI',
    plain: 'The other wheel — a general-purpose expression control sent as CC 1, value 0–127. What it *does* is up to the patch: vibrato depth, filter opening, anything.',
    why: 'Implementing mod wheel means routing one incoming CC to modulation destinations — your first taste of a mod matrix.',
    studio: 'The wheel you push up for drama.',
    uses: ['Vibrato depth', 'Filter opening', 'Any mapped destination'],
    mistake: 'Hard-wiring mod wheel to one destination forever — make it a routable source from the start.',
    remember: 'Mod wheel is CC 1: a knob whose meaning the patch decides.',
    related: ['cc', 'midi', 'lfo'],
    appears: [{ z: 5, node: 'n12' }],
    search: ['modulation', 'expression wheel'],
  },
  {
    id: 'cc', t: 'CC', full: 'Control Change', c: 'MIDI',
    plain: 'The MIDI message type for controls: a controller number (0–127) plus a value (0–127). CC 1 = mod wheel, CC 7 = volume, CC 64 = sustain pedal, CC 74 = brightness…',
    why: 'MIDI-learn, sustain pedal handling, hardware controller support — all CC parsing. Sustain (CC 64) in particular changes note-off behavior and trips up naive synths.',
    studio: 'Every knob and pedal on your controller that isn\'t a key.',
    uses: ['MIDI learn', 'Sustain pedal', 'Hardware mapping'],
    mistake: 'Ignoring CC 64 — with sustain down, note-offs must be deferred until pedal-up, or held chords cut dead.',
    remember: 'CC = numbered controller + value; CC 64 (sustain) changes note-off logic.',
    related: ['midi', 'mod-wheel', 'sustain'],
    appears: [{ z: 5, node: 'n10' }],
    aka: ['control change', 'cc64', 'midi cc'],
    search: ['controller', 'knob messages', 'sustain pedal'],
  },
  {
    id: 'program-change', t: 'program change', c: 'MIDI',
    plain: 'The MIDI message that says "switch to preset N" — one number, 0–127. Hardware-era preset switching that still works today.',
    why: 'Live players expect program changes to swap your plugin\'s presets — ideally without clicks or dropouts, which makes it a small thread-safety exercise.',
    studio: 'The patch-up/patch-down buttons on a stage keyboard.',
    uses: ['Live preset switching', 'Song-section changes'],
    mistake: 'Swapping state abruptly on the audio thread — preset changes should be handed over safely, tails respected.',
    remember: 'Program change = "preset N, please" — switch it glitch-free.',
    related: ['preset', 'midi', 'cc'],
    appears: [{ z: 5, node: 'n12' }],
    search: ['preset switch', 'patch change'],
  },

  /* ================= TOOLS / DEBUGGING ================= */
  {
    id: 'compiler', t: 'compiler', c: 'TOOLS',
    plain: 'The program that translates your C++ into machine code, checking every file for errors as it goes. It reports problems with a file, a line, and a message — often pointing one line *after* the real cause.',
    why: 'The compiler is your strictest bandmate: it catches typos, type mistakes and misuse before they can crash a DAW. Reading its messages calmly is a superpower.',
    studio: 'The mastering engineer who rejects the bounce — annoying until you realize they just saved your release.',
    uses: ['Every build', 'Error checking', 'Optimization (release builds)'],
    mistake: 'Reading the last error first. Fix error #1 — the rest are usually echoes.',
    remember: 'The compiler is on your side; read its first complaint first.',
    related: ['linker', 'compiler-error', 'build', 'source-file'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'e1' }],
    search: ['build', 'translate', 'gcc', 'clang', 'msvc'],
  },
  {
    id: 'linker', t: 'linker', c: 'TOOLS',
    plain: 'The build stage after compiling: it stitches all the compiled pieces into one binary, wiring every function call to an actual function body. Missing a body? "undefined reference."',
    why: '"Undefined reference" errors confuse everyone at first — they mean a promise (declaration) has no implementation, or a .cpp isn\'t in the build. Now you can read them.',
    studio: 'The tech who wires every panel to its circuit before the show — and reports any control connected to nothing.',
    uses: ['Final build step', 'Library linking', 'The undefined-reference error'],
    mistake: 'Hunting a linker error inside your syntax — it\'s not a typo, it\'s a missing definition or missing file in the build.',
    remember: 'Compiler checks files; linker connects them. "Undefined reference" = a promise with no body.',
    related: ['compiler', 'linker-error', 'cmake', 'source-file'],
    appears: [{ z: 1, node: 'l12' }, { z: 1, node: 'e3' }],
    search: ['undefined reference', 'ld', 'link'],
  },
  {
    id: 'compiler-error', t: 'compiler error', c: 'DEBUGGING',
    plain: 'A build failure the compiler catches in one file: missing semicolon, unknown name, wrong type. Comes with a file, line and message — the line is where it *noticed*, often just after the cause.',
    why: 'You\'ll see thousands. The skill: read the first error, check one line up, fix, rebuild. Walls of errors usually collapse from one fix.',
    studio: 'A channel with no signal: check the patch one point upstream of where the meter died.',
    uses: ['Everyday development', 'The e-challenges in Zone 1'],
    mistake: 'Panicking at 40 errors. They\'re echoes — fix the first.',
    remember: 'First error first; look one line above where it points.',
    related: ['compiler', 'linker-error', 'debugger'],
    appears: [{ z: 1, node: 'e1' }, { z: 1, node: 'e2' }],
    search: ['expected semicolon', 'not declared', 'build failed'],
  },
  {
    id: 'linker-error', t: 'linker error', c: 'DEBUGGING',
    plain: 'A build failure at the stitching stage — most famously "undefined reference to X": the function X was declared but no compiled body exists anywhere.',
    why: 'Two usual suspects: you never wrote the body, or its .cpp isn\'t listed in the build (CMake). No file/line given — which is exactly why beginners find it scary.',
    studio: 'A patch label pointing at an empty rack slot — the wiring plan promised gear that was never installed.',
    uses: ['Missing definitions', 'CMake file lists', 'Library setup'],
    mistake: 'Rewriting your header to fix it — the header (declaration) is fine; the body or the build list is what\'s missing.',
    remember: '"Undefined reference" = write the body, or add the .cpp to the build.',
    related: ['linker', 'compiler-error', 'cmake', 'source-file'],
    appears: [{ z: 1, node: 'e3' }],
    search: ['undefined reference', 'unresolved external'],
  },
  {
    id: 'debugger', t: 'debugger', c: 'DEBUGGING',
    plain: 'A tool that pauses your running plugin at chosen lines (breakpoints) so you can inspect every variable and step through code one line at a time.',
    why: 'Ten minutes in a debugger beats two hours of guessing. For crashes, it shows the exact line and the call stack that led there — including inside a running DAW.',
    studio: 'Soloing one channel and walking the signal chain node by node until you find where the hum enters.',
    uses: ['Crash diagnosis', 'Watching DSP values', 'Stepping through logic'],
    mistake: 'Debugging by println everywhere (and never on the audio thread — logging blocks!). Breakpoints are faster and safer.',
    remember: 'Breakpoints beat guesswork — attach the debugger before the third guess.',
    related: ['undefined-behavior', 'debug-build', 'ide', 'audio-thread'],
    appears: [{ z: 6, label: 'debugging crashes' }],
    search: ['breakpoint', 'step through', 'inspect', 'crash'],
  },
  {
    id: 'git', t: 'Git', c: 'TOOLS',
    plain: 'Version control: it snapshots your whole codebase every time you commit, so you can compare, branch, and roll back to any previous state. Runs locally; GitHub is where snapshots get shared.',
    why: 'DSP experiments break things — commit before each experiment and "undo" is always possible. Every serious plugin project lives in Git.',
    studio: 'Infinite undo plus named takes and comps — for code. "Filter working v3 FINAL" without the folder chaos.',
    uses: ['Save points before experiments', 'Branching ideas', 'Sharing via GitHub'],
    mistake: 'Committing rarely, in giant lumps. Commit small and often — snapshots are free.',
    remember: 'Commit before every experiment — Git makes fearless the default.',
    related: ['github', 'build', 'cmake'],
    appears: [{ z: 6, label: 'project workflow' }],
    search: ['version control', 'commit', 'undo', 'history'],
  },
  {
    id: 'github', t: 'GitHub', c: 'TOOLS',
    plain: 'The main website for hosting Git repositories: your code\'s cloud home, plus issues, pull requests and automated builds (Actions). Where JUCE itself and most audio open source lives.',
    why: 'Backup, collaboration, and CI builds of your plugin for Mac and Windows — plus the place you\'ll read other people\'s plugin code to learn.',
    studio: 'Cloud backup + collab space for sessions — but for repositories.',
    uses: ['Backup & sync', 'Reading JUCE source', 'CI builds (Actions)'],
    mistake: 'Confusing Git (the tool on your machine) with GitHub (a hosting service for it).',
    remember: 'Git is the tool; GitHub is its home on the internet.',
    related: ['git', 'cmake', 'build'],
    appears: [{ z: 6, label: 'sharing & CI' }],
    search: ['repository', 'repo', 'cloud code'],
  },
  {
    id: 'visual-studio', t: 'Visual Studio', c: 'TOOLS',
    plain: 'Microsoft\'s full IDE for Windows: code editor, MSVC compiler and a first-class debugger in one. The standard environment for building Windows VST3s. (Not the same thing as VS Code.)',
    why: 'On Windows, CMake generates Visual Studio projects, and its debugger attaches straight into a DAW running your plugin.',
    studio: 'The big studio console of Windows development — everything in one surface.',
    uses: ['Windows builds', 'Debugging inside DAWs', 'CMake integration'],
    mistake: 'Mixing it up with VS Code — Visual Studio is the heavyweight IDE; VS Code is the lightweight editor.',
    remember: 'Visual Studio = Windows IDE + compiler + debugger for your VST builds.',
    related: ['vs-code', 'ide', 'debugger', 'cmake'],
    appears: [{ z: 3, label: 'build environments' }],
    aka: ['msvc'],
    search: ['windows ide', 'microsoft'],
  },
  {
    id: 'vs-code', t: 'VS Code', full: 'Visual Studio Code', c: 'TOOLS',
    plain: 'Microsoft\'s free, lightweight code editor — extensions add C++ support, CMake tooling and debugging. Runs everywhere; the most popular editor in the world.',
    why: 'A comfortable cross-platform home for JUCE + CMake projects, especially with the C++ and CMake Tools extensions.',
    studio: 'A fast, modular project template — add just the devices you need.',
    uses: ['Editing C++', 'CMake workflows', 'Integrated terminal & Git'],
    mistake: 'Expecting a compiler in the box — VS Code is an editor; the C++ toolchain installs separately.',
    remember: 'VS Code is the light, extensible editor; bring your own compiler.',
    related: ['visual-studio', 'cursor-editor', 'ide', 'cmake'],
    appears: [{ z: 3, label: 'build environments' }],
    aka: ['vscode'],
    search: ['editor', 'code editor'],
  },
  {
    id: 'cursor-editor', t: 'Cursor', c: 'TOOLS',
    plain: 'An AI-first code editor built on VS Code: same interface and extensions, with an AI that reads your whole project and can write or edit code from chat instructions.',
    why: 'AI-assisted editors accelerate plugin work — but they\'re force multipliers, not replacements: you still review every audio-thread line the AI writes.',
    studio: 'An assistant engineer who knows the whole session — fast hands, but you still approve the mix.',
    uses: ['AI code edits', 'Explaining unfamiliar code', 'Refactoring'],
    mistake: 'Shipping AI-written callback code unreviewed — allocation and locks sneak in exactly there.',
    remember: 'AI editors accelerate you; real-time-safety review stays human.',
    related: ['vs-code', 'claude-code', 'ide'],
    appears: [{ z: 7, label: 'modern workflows' }],
    search: ['ai editor', 'ai coding'],
  },
  {
    id: 'claude-code', t: 'Claude Code', c: 'TOOLS',
    plain: 'Anthropic\'s AI coding agent: it reads a whole repository, plans, edits files, runs builds and tests from natural-language instructions — in a terminal, editor, or the cloud.',
    why: 'Agentic tools can scaffold a JUCE project, chase a linker error, or draft a DSP class. The skills this course teaches are what let you *direct and verify* that work.',
    studio: 'A session engineer who can also solder: give clear notes, then check the patchbay yourself.',
    uses: ['Project scaffolding', 'Build-error hunting', 'Test writing'],
    mistake: 'Delegating understanding. AI writes faster than you; it shouldn\'t understand your audio thread better than you.',
    remember: 'Direct the agent, verify the audio path — that\'s the workflow.',
    related: ['cursor-editor', 'vs-code', 'git'],
    appears: [{ z: 7, label: 'modern workflows' }],
    search: ['ai agent', 'anthropic', 'assistant'],
  },
  {
    id: 'cmake', t: 'CMake', c: 'TOOLS',
    plain: 'The build-system generator for modern C++ projects: a CMakeLists.txt file lists your sources, settings and targets, and CMake produces the actual platform build (Visual Studio, Xcode, Makefiles).',
    why: 'Modern JUCE is CMake-first: one text file declares your plugin, its formats (VST3/AU/Standalone) and its source files. Forgetting to list a .cpp here causes the classic linker error.',
    studio: 'The stage plot + input list: one document, and any venue\'s crew can wire your show.',
    uses: ['JUCE project setup', 'Adding source files', 'Choosing plugin formats'],
    mistake: 'Editing generated project files instead of CMakeLists.txt — regeneration erases your changes.',
    remember: 'CMakeLists.txt is the single source of truth for your build.',
    related: ['build', 'linker-error', 'juce', 'source-file'],
    appears: [{ z: 3, label: 'CMake project structure' }],
    search: ['build system', 'cmakelists', 'project file'],
  },
  {
    id: 'build', t: 'build', c: 'TOOLS',
    plain: 'The whole process of turning source code into a runnable plugin: compile every .cpp, link the pieces, bundle the result into a .vst3 (or AU, or app).',
    why: '"It builds" is the first gate every change must pass. Learning to read build output top-down turns red walls of text into a to-do list.',
    studio: 'The bounce: everything rendered down into the deliverable.',
    uses: ['Every development cycle', 'CI pipelines', 'Release packaging'],
    mistake: 'Ignoring warnings because "it built" — warnings are the compiler predicting your next bug.',
    remember: 'A build is compile + link + bundle — and warnings count.',
    related: ['compiler', 'linker', 'cmake', 'debug-build', 'release-build'],
    appears: [{ z: 3, label: 'first builds' }],
    search: ['compile', 'make', 'bounce'],
  },
  {
    id: 'debug-build', t: 'debug build', c: 'TOOLS',
    plain: 'A build with optimizations off and extra checks on: slower to run, but crashes point at exact lines and the debugger can see everything.',
    why: 'You develop in Debug so problems are visible and traceable. DSP can be 10× slower here — don\'t judge CPU performance from a Debug build.',
    studio: 'The rough mix with the click and guide vocals still in — for working, not releasing.',
    uses: ['Daily development', 'Crash tracing', 'Assertion checks'],
    mistake: 'Profiling CPU in Debug — always measure performance in Release.',
    remember: 'Develop in Debug; measure and ship in Release.',
    related: ['release-build', 'debugger', 'build'],
    appears: [{ z: 6, label: 'profiling & builds' }],
    search: ['slow build', 'assertions', 'development mode'],
  },
  {
    id: 'release-build', t: 'release build', c: 'TOOLS',
    plain: 'A build with full optimizations on and debug checks off: what users actually run. Fast — and nearly opaque to debuggers.',
    why: 'Real CPU usage, real denormal behavior, real performance — only a Release build tells the truth about them. Occasionally bugs appear *only* here (usually latent UB).',
    studio: 'The mastered bounce that goes out the door.',
    uses: ['Performance testing', 'Distribution', 'Final validation'],
    mistake: 'Never testing Release until launch day — optimizations can surface bugs Debug hid.',
    remember: 'Release is what ships — test it long before shipping day.',
    related: ['debug-build', 'build', 'cpu', 'undefined-behavior'],
    appears: [{ z: 6, label: 'profiling & packaging' }],
    search: ['optimized', 'final build', 'ship'],
  },

  /* ================= ARCHITECTURE / HARDWARE ================= */
  {
    id: 'cpu', t: 'CPU', full: 'Central Processing Unit', c: 'PERFORMANCE',
    plain: 'The chip that executes your code. Its speed budget is what the DAW\'s CPU meter shows — and what your plugin spends with every sample of math.',
    why: 'Producers judge plugins by the CPU meter. Per-voice costs, denormals, and work-per-sample decisions all land here.',
    studio: 'The DAW\'s CPU meter — the thing that ends sessions when it pins.',
    uses: ['Performance budgets', 'Voice count limits', 'Optimization targets'],
    mistake: 'Optimizing before measuring — profile first (in Release), then fix the actual hot spot.',
    remember: 'Every sample of DSP spends CPU — measure before optimizing.',
    related: ['ram', 'denormals', 'release-build', 'polyphony'],
    appears: [{ z: 6, label: 'profiling' }],
    search: ['processor', 'performance', 'meter', 'usage'],
  },
  {
    id: 'ram', t: 'RAM', full: 'Random Access Memory', c: 'PERFORMANCE',
    plain: 'The computer\'s fast working memory — where every running variable, buffer and loaded sample lives. Cleared when power goes off.',
    why: 'Sample libraries eat gigabytes of it; delay lines and wavetables take their share. Memory footprint is part of plugin design.',
    studio: 'How many sample libraries you can keep loaded before the machine groans.',
    uses: ['Sample streaming decisions', 'Buffer budgets', 'Preset storage'],
    mistake: 'Loading entire sample sets into RAM when streaming from disk (with a RAM preload buffer) scales better.',
    remember: 'RAM is fast, finite working memory — budget it like CPU.',
    related: ['memory', 'heap', 'cpu'],
    appears: [{ z: 7, label: 'sampler mission' }],
    search: ['memory', 'gigabytes', 'loaded samples'],
  },
  {
    id: 'gui', t: 'GUI', full: 'Graphical User Interface', c: 'ARCHITECTURE',
    plain: 'The visual front of your plugin — knobs, sliders, meters, graphics — everything users see and touch. In JUCE, built from Components inside the AudioProcessorEditor.',
    why: 'The GUI runs on the UI thread, may not exist at all, and must never be touched from audio code — its lifecycle shapes plugin architecture.',
    studio: 'The faceplate: what sells the unit and what hands actually touch.',
    uses: ['Knobs & sliders', 'Meters', 'Preset browsers', 'Resizable layouts'],
    mistake: 'Painting meters by reaching into audio data directly — meters read thread-safe copies, not the live buffer.',
    remember: 'The GUI is a separate, optional, slower world — bridge to it safely.',
    related: ['audioprocessoreditor', 'ui-thread', 'apvts'],
    appears: [{ z: 3, label: 'editor basics' }, { z: 6, label: 'responsive interfaces' }],
    search: ['interface', 'knobs', 'front panel', 'ui'],
  },
  {
    id: 'api', t: 'API', full: 'Application Programming Interface', c: 'ARCHITECTURE',
    plain: 'The set of functions and rules a library offers you — its control surface. "The JUCE API" means every class and method JUCE lets you call.',
    why: 'Plugin development is living inside other people\'s APIs: JUCE\'s classes, the VST3 spec, the OS audio system. Reading API docs is a daily skill.',
    studio: 'The jack panel of a rack unit: the manufacturer decided what you can patch; the manual tells you how.',
    uses: ['JUCE classes', 'Plugin format specs', 'OS audio systems'],
    mistake: 'Fighting an API instead of reading its docs — the intended path usually exists and is shorter.',
    remember: 'An API is a library\'s control surface — learn the intended patching.',
    related: ['juce', 'ide', 'gui'],
    appears: [{ z: 3, label: 'the JUCE API' }],
    search: ['library interface', 'docs', 'functions offered'],
  },
  {
    id: 'ide', t: 'IDE', full: 'Integrated Development Environment', c: 'TOOLS',
    plain: 'An all-in-one workspace for code: editor, build button, debugger and project browser in a single app. Visual Studio and Xcode are IDEs; VS Code is an editor that extensions grow into one.',
    why: 'You\'ll live in one. The build-run-debug loop inside an IDE is the plugin developer\'s daily rhythm.',
    studio: 'The full studio in one room: desk, monitors, outboard — no walking between rooms.',
    uses: ['Editing', 'Building', 'Debugging', 'Project navigation'],
    mistake: 'Tool-hopping weekly. Pick one, learn its debugger deeply, ship things.',
    remember: 'The IDE is your studio room — know where everything is without looking.',
    related: ['visual-studio', 'vs-code', 'debugger', 'build'],
    appears: [{ z: 3, label: 'build environments' }],
    search: ['editor', 'development environment', 'xcode'],
  }
);
