/* ============================================================
   SIGNAL DICTIONARY — part F: terms introduced by Zone 4.
   ============================================================ */

DICT.push(
  {
    id: 'nyquist', t: 'Nyquist frequency', c: 'DSP',
    plain: 'The highest frequency a sample rate can represent: exactly half the rate. A 48 kHz session can hold wobbles up to 24 kHz; ask the grid for anything faster and it folds back down as a wrong pitch instead of vanishing.',
    why: 'Every aliasing problem, every oversampling switch, and the choice of 44.1 kHz itself trace back to this one ceiling. Know it and half of digital audio\'s "weird rules" become obvious.',
    studio: 'The frame rate of a film: motion faster than half the frame rate doesn\'t disappear — the wagon wheel spins backwards. Nyquist is where audio\'s wheels start lying.',
    uses: ['Aliasing analysis', 'Choosing sample rates', 'Oversampling decisions', 'Filter design ceilings'],
    viz: { t: 'wave', type: 'samples', caption: 'the dots can only track wobbles slower than half their own speed' },
    mistake: 'Thinking content above Nyquist is simply cut off. It isn\'t — it reflects back into the audible range at inharmonic frequencies. Silence would be merciful; fold-back is the actual punishment.',
    remember: 'Half the sample rate is the ceiling — and what can\'t fit doesn\'t vanish, it folds.',
    related: ['sample-rate', 'aliasing', 'oversampling', 'harmonics'],
    appears: [{ z: 4, node: 'd2' }, { z: 4, node: 'd8' }],
    aka: ['nyquist limit', 'folding frequency'],
    search: ['half sample rate', 'frequency ceiling', 'fold back', 'highest pitch', 'nyquist rate'],
  },
  {
    id: 'harmonics', t: 'harmonics', c: 'DSP',
    plain: 'The whole-number multiples of a note\'s fundamental frequency — counting the fundamental itself as the 1st: play 440 Hz and the 2nd harmonic sits at 880, the 3rd at 1320, the 4th at 1760… Their relative strengths are the recipe that makes a saw bright, a square hollow, a sine pure.',
    why: 'Waveform choice, filter sweeps, distortion, clipping and aliasing are all stories about harmonics — which ones exist, which get removed, which get added, which fold. It\'s the vocabulary of timbre.',
    studio: 'The overtones that make a Strat and a Les Paul play the same note and sound nothing alike. Same fundamental, different recipe.',
    uses: ['Waveform character', 'Subtractive filtering', 'Why clipping sounds harsh', 'Aliasing analysis'],
    viz: { t: 'wave', type: 'saw', caption: 'sharp corners = strong high harmonics — the saw has every one' },
    mistake: 'Hearing "harmonics" as always pleasant. Clipping piles harsh new HIGH harmonics onto a tone — and digitally, any that pass Nyquist fold back to wrong, inharmonic places; aliasing lands at wrong places outright.',
    remember: 'A waveform\'s shape is a harmonic recipe — corners mean strong highs.',
    related: ['waveform', 'frequency', 'clipping', 'aliasing', 'cutoff'],
    appears: [{ z: 4, node: 'd7' }, { z: 4, node: 'd8' }, { z: 4, node: 'd10' }],
    aka: ['overtones', 'harmonic partials', 'harmonic series'],
    search: ['overtones', 'timbre', 'bright sound', 'why saw sounds bright'],
  },
  {
    id: 'white-noise', t: 'white noise', c: 'SYNTHS',
    plain: 'A signal where every sample is a fresh random value in ±1 — no cycle, no pitch, all frequencies at once at equal average energy. The "hiss" oscillator on nearly every subtractive synth.',
    why: 'It\'s the one generator that ignores phase entirely, the raw material of snares, hats, risers and wind — and its ±1 recentering is a classic first DC-offset bug.',
    studio: 'The ocean-hiss layer under a snare, the riser before the drop, the breath in a flute patch — all one random-number generator wearing different envelopes.',
    uses: ['Snares & hats', 'Risers & FX', 'Breath & texture layers', 'Testing filters'],
    mistake: 'Generating with nextFloat() alone: that\'s 0..1, all positive — noise riding a giant DC offset that leans the woofer and clicks at every note edge. Stretch and recenter: × 2 − 1.',
    remember: 'Random ±1 per sample: no phase, no pitch, every frequency at once.',
    related: ['waveform', 'oscillator', 'dc-offset', 'envelope'],
    appears: [{ z: 4, node: 'd7' }, { z: 4, node: 'db1' }, { z: 4, node: 'p10' }],
    aka: ['noise', 'noise oscillator'],
    search: ['hiss', 'random samples', 'snare noise', 'noise generator'],
  },
  {
    id: 'clipping', t: 'clipping', c: 'AUDIO ENG',
    plain: 'What happens when samples try to leave the ±1.0 full-scale range: they\'re clamped at the boundary and the waveform\'s round peaks become flat tops. Flat tops are sharp corners — new harsh harmonics that were never in the music.',
    why: 'It\'s the most audible failure in digital audio, the reason gain staging exists in code, and — controlled and intentional — the engine inside most distortion plugins. Same math, opposite intent.',
    studio: 'The master bus red light, made of arithmetic. Analog clipping saturated gradually; digital clipping is a doorframe that flattens every head taller than the frame.',
    uses: ['Why mixes crunch', 'Output safety clamps', 'Distortion by design', 'Gain staging'],
    viz: { t: 'clipwave' },
    mistake: 'Believing floats clip at 1.0 inside the plugin. They carry 3.7 through your DSP just fine — the slicing happens at the boundary out of float land. That\'s why a trim after a hot plugin can rescue the level.',
    remember: 'Past ±1.0 the peaks go flat — and flat tops are harmonics you never asked for.',
    related: ['gain', 'headroom', 'decibel', 'harmonics', 'mixing'],
    appears: [{ z: 4, node: 'd10' }, { z: 4, node: 'db4' }, { z: 4, node: 'boss4' }],
    aka: ['digital clipping', 'hard clipping', 'overs'],
    search: ['distortion', 'red light', 'too loud', 'flat top', 'jlimit'],
  },
  {
    id: 'headroom', t: 'headroom', c: 'AUDIO ENG',
    plain: 'The safety margin between your signal\'s peaks and the ±1.0 ceiling. Generating a sine at 0.25 instead of 1.0 leaves 12 dB of headroom — space for sums, envelopes and surprises before anything clips.',
    why: 'Every clean DSP chain guards its headroom on purpose: scale each voice, plan the worst-case sum, and the output clamp never engages in normal use.',
    studio: 'Recording at −18 dBFS instead of slamming the converter: the same discipline, in code. Room to move is room to mix.',
    uses: ['Voice levels (the 0.25f)', 'Bus trims after summing', 'Worst-case peak planning'],
    mistake: 'Treating the output clamp as the loudness plan. If the clamp engages constantly, it IS distortion — headroom upstream is the real protection; the clamp is only the seatbelt.',
    remember: 'Leave space below the ceiling on purpose — sums and envelopes will spend it.',
    related: ['clipping', 'gain', 'decibel', 'mixing'],
    appears: [{ z: 4, node: 'd4' }, { z: 4, node: 'd10' }, { z: 4, node: 'd11' }],
    search: ['safety margin', 'gain staging', 'how loud', 'peak level'],
  },
  {
    id: 'mixing', t: 'mixing (summing)', c: 'DSP',
    plain: 'Combining digital signals by adding them, sample by sample. Every bus, every layer, every chord in a polyphonic synth is per-sample addition — the entire craft of mixing sits on a plus sign.',
    why: 'Because peaks add too: N full-scale sources can sum to N, straight through the ceiling. Every sum in your code needs a gain plan — scale the sources or trim the bus.',
    studio: 'Air does it first: kick and vocal in one room sum into one pressure wave at your eardrum. The console\'s bus is the room, in arithmetic form.',
    uses: ['Layering oscillators', 'Polyphony (one voice per note, summed)', 'DAW buses', 'Wet/dry blends'],
    viz: { t: 'mixsum' },
    mistake: 'Believing digital summing "degrades" audio where analog "glues" it. The addition is bit-exact — desks add their own gentle distortion and crosstalk, a flavor. A plus sign has no quality knob.',
    remember: 'Mixing is addition; the skill is the gain plan around the plus sign.',
    related: ['clipping', 'headroom', 'gain', 'phase', 'polyphony'],
    appears: [{ z: 4, node: 'd11' }, { z: 4, node: 'dc2' }, { z: 4, node: 'boss4' }],
    aka: ['summing', 'mix bus'],
    search: ['combine sounds', 'layer', 'add signals', 'bus'],
  },
  {
    id: 'stereo', t: 'stereo', c: 'AUDIO ENG',
    plain: 'Two independent mono sample streams — channel 0 (left) and channel 1 (right) — on one clock. There\'s no "stereo sample": identical lanes sound center, differences create width and placement, opposite polarity cancels in mono.',
    why: 'Every buffer loop you write walks these lanes, every pan knob is a two-gain recipe across them, and mono compatibility — the L+R sum test — decides how your mix survives clubs and phone speakers.',
    studio: 'Two singers reading the same line, one at each ear: unison feels center, a level difference slides it sideways, an inverted copy vanishes when the room sums them.',
    uses: ['Channel loops', 'Panning', 'Width effects', 'Mono fold-down checks'],
    viz: { t: 'stereopan' },
    mistake: 'Processing only channel 0 and shipping — the right side stays dry or silent. Every lane gets written, every block: the channel loop is load-bearing, not decoration.',
    remember: 'Two mono lanes: same = center, different = wide, opposite = gone in mono.',
    related: ['audio-buffer', 'panning', 'mixing', 'phase'],
    appears: [{ z: 4, node: 'd12' }, { z: 3, label: 'the channel loop' }],
    aka: ['stereo field', 'mono compatibility', 'L/R'],
    search: ['left right', 'width', 'image', 'mono', 'channels'],
  },
  {
    id: 'panning', t: 'panning', c: 'AUDIO ENG',
    plain: 'Placing one sound in the stereo image by sending it to left and right at different gains. Done right, it\'s constant-power panning — cos/sin gains that keep loudness even as the sound sweeps through center.',
    why: 'The naive linear pan law (pan and 1−pan) dips about 3 dB at center — the classic "hole in the middle." One cos/sin pair fixes it, and explains the pan-law setting in your DAW.',
    studio: 'The pan pot on every console channel: one source, two bus sends, and the level DIFFERENCE is the position your brain hears.',
    uses: ['Pan knobs', 'Auto-panners', 'Stereo spread in synth voices'],
    mistake: 'Linear gains: L = s·pan, R = s·(1−pan). Besides dipping at center, that particular pairing puts silence LEFT at pan = 0 — sides swapped AND a hole in the middle.',
    remember: 'One source, two gains — cos/sin keeps the power constant across the sweep.',
    related: ['stereo', 'gain', 'mixing'],
    appears: [{ z: 4, node: 'd12' }, { z: 4, node: 'dc4' }],
    aka: ['pan law', 'constant-power panning'],
    search: ['pan knob', 'place sound', 'left right position', 'hole in the middle'],
  },
  {
    id: 'zipper-noise', t: 'zipper noise', c: 'DEBUGGING',
    plain: 'The crackling flutter heard when a parameter changes in audible steps: each value jump draws a vertical cliff into the waveform, each cliff is a corner, each corner is a click — repeated fast, a zipper.',
    why: 'It\'s the audible symptom that tells you a continuous parameter isn\'t smoothed — and the reason SmoothedValue calls getNextValue() per SAMPLE, not per block.',
    studio: 'A fader with hard detents: every notch thunks. Smoothing is the motorized fader that glides through every level in between.',
    uses: ['Diagnosing unsmoothed gain/pan/cutoff', 'Judging ramp lengths', 'QA before release'],
    viz: { t: 'stepramp' },
    mistake: 'Curing it by smoothing EVERYTHING — including the waveform selector, which then "sounds mushy between positions." Glide continuous parameters; snap discrete switches.',
    remember: 'Jumps are corners; corners are clicks. If the knob crackles, the value is stepping.',
    related: ['parameter-smoothing', 'harmonics', 'parameter'],
    appears: [{ z: 4, node: 'd13' }, { z: 3, node: 'j12' }, { z: 4, node: 'boss4' }],
    aka: ['zippering', 'parameter clicks'],
    search: ['crackle when turning knob', 'clicks on automation', 'stepped parameter'],
  },
  {
    id: 'modulation', t: 'modulation', c: 'SYNTHS',
    plain: 'One signal steering a parameter of another: an envelope shaping gain per note, an LFO wobbling pitch or cutoff forever. You hear the modulator only through its effect on the sound it steers.',
    why: 'Motion is what reads as "alive" in sound design — and every mod routing on every synth reduces to three choices: rate (or trigger), depth, destination. Learn the pattern once, read every mod matrix forever.',
    studio: 'A session robot hired to turn one knob back and forth in perfect time. Rate is its wrist speed, depth its twist, destination the knob you point it at.',
    uses: ['Tremolo (LFO→gain)', 'Vibrato (LFO→pitch)', 'Filter wobble (LFO→cutoff)', 'Envelope→anything'],
    viz: { t: 'lfomod' },
    mistake: 'Wiring a raw −1..+1 LFO straight into a gain: half of every cycle the polarity flips and the sound fully mutes at the crossings. Re-range to 0..1 and scale by depth first.',
    remember: 'Rate, depth, destination — every mod routing ever, three words.',
    related: ['lfo', 'envelope', 'oscillator', 'parameter'],
    appears: [{ z: 4, node: 'd14' }, { z: 4, node: 'dr2' }, { z: 5, node: 'n13' }],
    aka: ['mod routing', 'mod matrix', 'control signal'],
    search: ['movement', 'wobble', 'tremolo', 'vibrato', 'lfo to filter'],
  }
);
